/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.workflow.db.tables.pojos;


import com.ke.bella.workflow.db.repo.Operator;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TenantsDB implements Operator, Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        tenantId;
    private String        tenantName;
    private Long          cuid;
    private String        cuName;
    private LocalDateTime ctime;
    private Long          muid;
    private String        muName;
    private LocalDateTime mtime;

    public TenantsDB() {}

    public TenantsDB(TenantsDB value) {
        this.id = value.id;
        this.tenantId = value.tenantId;
        this.tenantName = value.tenantName;
        this.cuid = value.cuid;
        this.cuName = value.cuName;
        this.ctime = value.ctime;
        this.muid = value.muid;
        this.muName = value.muName;
        this.mtime = value.mtime;
    }

    public TenantsDB(
        Long          id,
        String        tenantId,
        String        tenantName,
        Long          cuid,
        String        cuName,
        LocalDateTime ctime,
        Long          muid,
        String        muName,
        LocalDateTime mtime
    ) {
        this.id = id;
        this.tenantId = tenantId;
        this.tenantName = tenantName;
        this.cuid = cuid;
        this.cuName = cuName;
        this.ctime = ctime;
        this.muid = muid;
        this.muName = muName;
        this.mtime = mtime;
    }

    /**
     * Getter for <code>tenants.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>tenants.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>tenants.tenant_id</code>.
     */
    public String getTenantId() {
        return this.tenantId;
    }

    /**
     * Setter for <code>tenants.tenant_id</code>.
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * Getter for <code>tenants.tenant_name</code>.
     */
    public String getTenantName() {
        return this.tenantName;
    }

    /**
     * Setter for <code>tenants.tenant_name</code>.
     */
    public void setTenantName(String tenantName) {
        this.tenantName = tenantName;
    }

    /**
     * Getter for <code>tenants.cuid</code>.
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>tenants.cuid</code>.
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>tenants.cu_name</code>.
     */
    public String getCuName() {
        return this.cuName;
    }

    /**
     * Setter for <code>tenants.cu_name</code>.
     */
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    /**
     * Getter for <code>tenants.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>tenants.ctime</code>.
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>tenants.muid</code>.
     */
    public Long getMuid() {
        return this.muid;
    }

    /**
     * Setter for <code>tenants.muid</code>.
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    /**
     * Getter for <code>tenants.mu_name</code>.
     */
    public String getMuName() {
        return this.muName;
    }

    /**
     * Setter for <code>tenants.mu_name</code>.
     */
    public void setMuName(String muName) {
        this.muName = muName;
    }

    /**
     * Getter for <code>tenants.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>tenants.mtime</code>.
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TenantsDB (");

        sb.append(id);
        sb.append(", ").append(tenantId);
        sb.append(", ").append(tenantName);
        sb.append(", ").append(cuid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(muid);
        sb.append(", ").append(muName);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
