/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.workflow.db.tables.pojos;


import com.ke.bella.workflow.db.repo.Operator;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkflowsDB implements Operator, Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        tenantId;
    private String        workflowId;
    private String        graph;
    private Long          version;
    private Long          cuid;
    private String        cuName;
    private LocalDateTime ctime;
    private Long          muid;
    private String        muName;
    private LocalDateTime mtime;

    public WorkflowsDB() {}

    public WorkflowsDB(WorkflowsDB value) {
        this.id = value.id;
        this.tenantId = value.tenantId;
        this.workflowId = value.workflowId;
        this.graph = value.graph;
        this.version = value.version;
        this.cuid = value.cuid;
        this.cuName = value.cuName;
        this.ctime = value.ctime;
        this.muid = value.muid;
        this.muName = value.muName;
        this.mtime = value.mtime;
    }

    public WorkflowsDB(
        Long          id,
        String        tenantId,
        String        workflowId,
        String        graph,
        Long          version,
        Long          cuid,
        String        cuName,
        LocalDateTime ctime,
        Long          muid,
        String        muName,
        LocalDateTime mtime
    ) {
        this.id = id;
        this.tenantId = tenantId;
        this.workflowId = workflowId;
        this.graph = graph;
        this.version = version;
        this.cuid = cuid;
        this.cuName = cuName;
        this.ctime = ctime;
        this.muid = muid;
        this.muName = muName;
        this.mtime = mtime;
    }

    /**
     * Getter for <code>workflows.id</code>. workflow配置自增主键
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>workflows.id</code>. workflow配置自增主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>workflows.tenant_id</code>. 租户id
     */
    public String getTenantId() {
        return this.tenantId;
    }

    /**
     * Setter for <code>workflows.tenant_id</code>. 租户id
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * Getter for <code>workflows.workflow_id</code>.
     */
    public String getWorkflowId() {
        return this.workflowId;
    }

    /**
     * Setter for <code>workflows.workflow_id</code>.
     */
    public void setWorkflowId(String workflowId) {
        this.workflowId = workflowId;
    }

    /**
     * Getter for <code>workflows.graph</code>. 工作流DAG配置
     */
    public String getGraph() {
        return this.graph;
    }

    /**
     * Setter for <code>workflows.graph</code>. 工作流DAG配置
     */
    public void setGraph(String graph) {
        this.graph = graph;
    }

    /**
     * Getter for <code>workflows.version</code>. 工作流版本，0: draft, &gt;0 正式版时间戳
     */
    public Long getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>workflows.version</code>. 工作流版本，0: draft, &gt;0 正式版时间戳
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * Getter for <code>workflows.cuid</code>.
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>workflows.cuid</code>.
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>workflows.cu_name</code>.
     */
    public String getCuName() {
        return this.cuName;
    }

    /**
     * Setter for <code>workflows.cu_name</code>.
     */
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    /**
     * Getter for <code>workflows.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>workflows.ctime</code>.
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>workflows.muid</code>.
     */
    public Long getMuid() {
        return this.muid;
    }

    /**
     * Setter for <code>workflows.muid</code>.
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    /**
     * Getter for <code>workflows.mu_name</code>.
     */
    public String getMuName() {
        return this.muName;
    }

    /**
     * Setter for <code>workflows.mu_name</code>.
     */
    public void setMuName(String muName) {
        this.muName = muName;
    }

    /**
     * Getter for <code>workflows.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>workflows.mtime</code>.
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WorkflowsDB (");

        sb.append(id);
        sb.append(", ").append(tenantId);
        sb.append(", ").append(workflowId);
        sb.append(", ").append(graph);
        sb.append(", ").append(version);
        sb.append(", ").append(cuid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(muid);
        sb.append(", ").append(muName);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
