/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.workflow.db.tables.records;


import com.ke.bella.workflow.db.repo.Operator;
import com.ke.bella.workflow.db.tables.Tenant;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TenantRecord extends UpdatableRecordImpl<TenantRecord> implements Operator, Record9<Long, String, String, Long, String, LocalDateTime, Long, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>tenant.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>tenant.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>tenant.tenant_id</code>.
     */
    public void setTenantId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tenant.tenant_id</code>.
     */
    public String getTenantId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tenant.tenant_name</code>.
     */
    public void setTenantName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tenant.tenant_name</code>.
     */
    public String getTenantName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tenant.cuid</code>.
     */
    public void setCuid(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>tenant.cuid</code>.
     */
    public Long getCuid() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>tenant.cu_name</code>.
     */
    public void setCuName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>tenant.cu_name</code>.
     */
    public String getCuName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>tenant.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>tenant.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>tenant.muid</code>.
     */
    public void setMuid(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>tenant.muid</code>.
     */
    public Long getMuid() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>tenant.mu_name</code>.
     */
    public void setMuName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>tenant.mu_name</code>.
     */
    public String getMuName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>tenant.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>tenant.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, Long, String, LocalDateTime, Long, String, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, String, String, Long, String, LocalDateTime, Long, String, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Tenant.TENANT.ID;
    }

    @Override
    public Field<String> field2() {
        return Tenant.TENANT.TENANT_ID;
    }

    @Override
    public Field<String> field3() {
        return Tenant.TENANT.TENANT_NAME;
    }

    @Override
    public Field<Long> field4() {
        return Tenant.TENANT.CUID;
    }

    @Override
    public Field<String> field5() {
        return Tenant.TENANT.CU_NAME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Tenant.TENANT.CTIME;
    }

    @Override
    public Field<Long> field7() {
        return Tenant.TENANT.MUID;
    }

    @Override
    public Field<String> field8() {
        return Tenant.TENANT.MU_NAME;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return Tenant.TENANT.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTenantId();
    }

    @Override
    public String component3() {
        return getTenantName();
    }

    @Override
    public Long component4() {
        return getCuid();
    }

    @Override
    public String component5() {
        return getCuName();
    }

    @Override
    public LocalDateTime component6() {
        return getCtime();
    }

    @Override
    public Long component7() {
        return getMuid();
    }

    @Override
    public String component8() {
        return getMuName();
    }

    @Override
    public LocalDateTime component9() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTenantId();
    }

    @Override
    public String value3() {
        return getTenantName();
    }

    @Override
    public Long value4() {
        return getCuid();
    }

    @Override
    public String value5() {
        return getCuName();
    }

    @Override
    public LocalDateTime value6() {
        return getCtime();
    }

    @Override
    public Long value7() {
        return getMuid();
    }

    @Override
    public String value8() {
        return getMuName();
    }

    @Override
    public LocalDateTime value9() {
        return getMtime();
    }

    @Override
    public TenantRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TenantRecord value2(String value) {
        setTenantId(value);
        return this;
    }

    @Override
    public TenantRecord value3(String value) {
        setTenantName(value);
        return this;
    }

    @Override
    public TenantRecord value4(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public TenantRecord value5(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public TenantRecord value6(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public TenantRecord value7(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public TenantRecord value8(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public TenantRecord value9(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public TenantRecord values(Long value1, String value2, String value3, Long value4, String value5, LocalDateTime value6, Long value7, String value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TenantRecord
     */
    public TenantRecord() {
        super(Tenant.TENANT);
    }

    /**
     * Create a detached, initialised TenantRecord
     */
    public TenantRecord(Long id, String tenantId, String tenantName, Long cuid, String cuName, LocalDateTime ctime, Long muid, String muName, LocalDateTime mtime) {
        super(Tenant.TENANT);

        setId(id);
        setTenantId(tenantId);
        setTenantName(tenantName);
        setCuid(cuid);
        setCuName(cuName);
        setCtime(ctime);
        setMuid(muid);
        setMuName(muName);
        setMtime(mtime);
    }
}
