/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.workflow.db.tables.records;


import com.ke.bella.workflow.db.tables.WorkflowNodeRuns;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkflowNodeRunsRecord extends UpdatableRecordImpl<WorkflowNodeRunsRecord> implements Record19<Long, String, String, String, String, String, String, String, String, String, String, String, Long, Long, String, LocalDateTime, Long, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>workflow_node_runs.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>workflow_node_runs.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>workflow_node_runs.tenant_id</code>.
     */
    public void setTenantId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>workflow_node_runs.tenant_id</code>.
     */
    public String getTenantId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>workflow_node_runs.workflow_id</code>.
     */
    public void setWorkflowId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>workflow_node_runs.workflow_id</code>.
     */
    public String getWorkflowId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>workflow_node_runs.workflow_run_id</code>.
     */
    public void setWorkflowRunId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>workflow_node_runs.workflow_run_id</code>.
     */
    public String getWorkflowRunId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>workflow_node_runs.node_id</code>.
     */
    public void setNodeId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>workflow_node_runs.node_id</code>.
     */
    public String getNodeId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>workflow_node_runs.node_type</code>.
     */
    public void setNodeType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>workflow_node_runs.node_type</code>.
     */
    public String getNodeType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>workflow_node_runs.title</code>.
     */
    public void setTitle(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>workflow_node_runs.title</code>.
     */
    public String getTitle() {
        return (String) get(6);
    }

    /**
     * Setter for <code>workflow_node_runs.inputs</code>.
     */
    public void setInputs(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>workflow_node_runs.inputs</code>.
     */
    public String getInputs() {
        return (String) get(7);
    }

    /**
     * Setter for <code>workflow_node_runs.outputs</code>.
     */
    public void setOutputs(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>workflow_node_runs.outputs</code>.
     */
    public String getOutputs() {
        return (String) get(8);
    }

    /**
     * Setter for <code>workflow_node_runs.error</code>.
     */
    public void setError(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>workflow_node_runs.error</code>.
     */
    public String getError() {
        return (String) get(9);
    }

    /**
     * Setter for <code>workflow_node_runs.process_data</code>.
     */
    public void setProcessData(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>workflow_node_runs.process_data</code>.
     */
    public String getProcessData() {
        return (String) get(10);
    }

    /**
     * Setter for <code>workflow_node_runs.status</code>.
     */
    public void setStatus(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>workflow_node_runs.status</code>.
     */
    public String getStatus() {
        return (String) get(11);
    }

    /**
     * Setter for <code>workflow_node_runs.elapsed_time</code>.
     */
    public void setElapsedTime(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>workflow_node_runs.elapsed_time</code>.
     */
    public Long getElapsedTime() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>workflow_node_runs.cuid</code>.
     */
    public void setCuid(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>workflow_node_runs.cuid</code>.
     */
    public Long getCuid() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>workflow_node_runs.cu_name</code>.
     */
    public void setCuName(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>workflow_node_runs.cu_name</code>.
     */
    public String getCuName() {
        return (String) get(14);
    }

    /**
     * Setter for <code>workflow_node_runs.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>workflow_node_runs.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>workflow_node_runs.muid</code>.
     */
    public void setMuid(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>workflow_node_runs.muid</code>.
     */
    public Long getMuid() {
        return (Long) get(16);
    }

    /**
     * Setter for <code>workflow_node_runs.mu_name</code>.
     */
    public void setMuName(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>workflow_node_runs.mu_name</code>.
     */
    public String getMuName() {
        return (String) get(17);
    }

    /**
     * Setter for <code>workflow_node_runs.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(18, value);
    }

    /**
     * Getter for <code>workflow_node_runs.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row19<Long, String, String, String, String, String, String, String, String, String, String, String, Long, Long, String, LocalDateTime, Long, String, LocalDateTime> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    @Override
    public Row19<Long, String, String, String, String, String, String, String, String, String, String, String, Long, Long, String, LocalDateTime, Long, String, LocalDateTime> valuesRow() {
        return (Row19) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return WorkflowNodeRuns.WORKFLOW_NODE_RUNS.ID;
    }

    @Override
    public Field<String> field2() {
        return WorkflowNodeRuns.WORKFLOW_NODE_RUNS.TENANT_ID;
    }

    @Override
    public Field<String> field3() {
        return WorkflowNodeRuns.WORKFLOW_NODE_RUNS.WORKFLOW_ID;
    }

    @Override
    public Field<String> field4() {
        return WorkflowNodeRuns.WORKFLOW_NODE_RUNS.WORKFLOW_RUN_ID;
    }

    @Override
    public Field<String> field5() {
        return WorkflowNodeRuns.WORKFLOW_NODE_RUNS.NODE_ID;
    }

    @Override
    public Field<String> field6() {
        return WorkflowNodeRuns.WORKFLOW_NODE_RUNS.NODE_TYPE;
    }

    @Override
    public Field<String> field7() {
        return WorkflowNodeRuns.WORKFLOW_NODE_RUNS.TITLE;
    }

    @Override
    public Field<String> field8() {
        return WorkflowNodeRuns.WORKFLOW_NODE_RUNS.INPUTS;
    }

    @Override
    public Field<String> field9() {
        return WorkflowNodeRuns.WORKFLOW_NODE_RUNS.OUTPUTS;
    }

    @Override
    public Field<String> field10() {
        return WorkflowNodeRuns.WORKFLOW_NODE_RUNS.ERROR;
    }

    @Override
    public Field<String> field11() {
        return WorkflowNodeRuns.WORKFLOW_NODE_RUNS.PROCESS_DATA;
    }

    @Override
    public Field<String> field12() {
        return WorkflowNodeRuns.WORKFLOW_NODE_RUNS.STATUS;
    }

    @Override
    public Field<Long> field13() {
        return WorkflowNodeRuns.WORKFLOW_NODE_RUNS.ELAPSED_TIME;
    }

    @Override
    public Field<Long> field14() {
        return WorkflowNodeRuns.WORKFLOW_NODE_RUNS.CUID;
    }

    @Override
    public Field<String> field15() {
        return WorkflowNodeRuns.WORKFLOW_NODE_RUNS.CU_NAME;
    }

    @Override
    public Field<LocalDateTime> field16() {
        return WorkflowNodeRuns.WORKFLOW_NODE_RUNS.CTIME;
    }

    @Override
    public Field<Long> field17() {
        return WorkflowNodeRuns.WORKFLOW_NODE_RUNS.MUID;
    }

    @Override
    public Field<String> field18() {
        return WorkflowNodeRuns.WORKFLOW_NODE_RUNS.MU_NAME;
    }

    @Override
    public Field<LocalDateTime> field19() {
        return WorkflowNodeRuns.WORKFLOW_NODE_RUNS.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTenantId();
    }

    @Override
    public String component3() {
        return getWorkflowId();
    }

    @Override
    public String component4() {
        return getWorkflowRunId();
    }

    @Override
    public String component5() {
        return getNodeId();
    }

    @Override
    public String component6() {
        return getNodeType();
    }

    @Override
    public String component7() {
        return getTitle();
    }

    @Override
    public String component8() {
        return getInputs();
    }

    @Override
    public String component9() {
        return getOutputs();
    }

    @Override
    public String component10() {
        return getError();
    }

    @Override
    public String component11() {
        return getProcessData();
    }

    @Override
    public String component12() {
        return getStatus();
    }

    @Override
    public Long component13() {
        return getElapsedTime();
    }

    @Override
    public Long component14() {
        return getCuid();
    }

    @Override
    public String component15() {
        return getCuName();
    }

    @Override
    public LocalDateTime component16() {
        return getCtime();
    }

    @Override
    public Long component17() {
        return getMuid();
    }

    @Override
    public String component18() {
        return getMuName();
    }

    @Override
    public LocalDateTime component19() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTenantId();
    }

    @Override
    public String value3() {
        return getWorkflowId();
    }

    @Override
    public String value4() {
        return getWorkflowRunId();
    }

    @Override
    public String value5() {
        return getNodeId();
    }

    @Override
    public String value6() {
        return getNodeType();
    }

    @Override
    public String value7() {
        return getTitle();
    }

    @Override
    public String value8() {
        return getInputs();
    }

    @Override
    public String value9() {
        return getOutputs();
    }

    @Override
    public String value10() {
        return getError();
    }

    @Override
    public String value11() {
        return getProcessData();
    }

    @Override
    public String value12() {
        return getStatus();
    }

    @Override
    public Long value13() {
        return getElapsedTime();
    }

    @Override
    public Long value14() {
        return getCuid();
    }

    @Override
    public String value15() {
        return getCuName();
    }

    @Override
    public LocalDateTime value16() {
        return getCtime();
    }

    @Override
    public Long value17() {
        return getMuid();
    }

    @Override
    public String value18() {
        return getMuName();
    }

    @Override
    public LocalDateTime value19() {
        return getMtime();
    }

    @Override
    public WorkflowNodeRunsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public WorkflowNodeRunsRecord value2(String value) {
        setTenantId(value);
        return this;
    }

    @Override
    public WorkflowNodeRunsRecord value3(String value) {
        setWorkflowId(value);
        return this;
    }

    @Override
    public WorkflowNodeRunsRecord value4(String value) {
        setWorkflowRunId(value);
        return this;
    }

    @Override
    public WorkflowNodeRunsRecord value5(String value) {
        setNodeId(value);
        return this;
    }

    @Override
    public WorkflowNodeRunsRecord value6(String value) {
        setNodeType(value);
        return this;
    }

    @Override
    public WorkflowNodeRunsRecord value7(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public WorkflowNodeRunsRecord value8(String value) {
        setInputs(value);
        return this;
    }

    @Override
    public WorkflowNodeRunsRecord value9(String value) {
        setOutputs(value);
        return this;
    }

    @Override
    public WorkflowNodeRunsRecord value10(String value) {
        setError(value);
        return this;
    }

    @Override
    public WorkflowNodeRunsRecord value11(String value) {
        setProcessData(value);
        return this;
    }

    @Override
    public WorkflowNodeRunsRecord value12(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public WorkflowNodeRunsRecord value13(Long value) {
        setElapsedTime(value);
        return this;
    }

    @Override
    public WorkflowNodeRunsRecord value14(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public WorkflowNodeRunsRecord value15(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public WorkflowNodeRunsRecord value16(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public WorkflowNodeRunsRecord value17(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public WorkflowNodeRunsRecord value18(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public WorkflowNodeRunsRecord value19(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public WorkflowNodeRunsRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, Long value13, Long value14, String value15, LocalDateTime value16, Long value17, String value18, LocalDateTime value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkflowNodeRunsRecord
     */
    public WorkflowNodeRunsRecord() {
        super(WorkflowNodeRuns.WORKFLOW_NODE_RUNS);
    }

    /**
     * Create a detached, initialised WorkflowNodeRunsRecord
     */
    public WorkflowNodeRunsRecord(Long id, String tenantId, String workflowId, String workflowRunId, String nodeId, String nodeType, String title, String inputs, String outputs, String error, String processData, String status, Long elapsedTime, Long cuid, String cuName, LocalDateTime ctime, Long muid, String muName, LocalDateTime mtime) {
        super(WorkflowNodeRuns.WORKFLOW_NODE_RUNS);

        setId(id);
        setTenantId(tenantId);
        setWorkflowId(workflowId);
        setWorkflowRunId(workflowRunId);
        setNodeId(nodeId);
        setNodeType(nodeType);
        setTitle(title);
        setInputs(inputs);
        setOutputs(outputs);
        setError(error);
        setProcessData(processData);
        setStatus(status);
        setElapsedTime(elapsedTime);
        setCuid(cuid);
        setCuName(cuName);
        setCtime(ctime);
        setMuid(muid);
        setMuName(muName);
        setMtime(mtime);
    }
}
