/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.workflow.db.tables.records;


import com.ke.bella.workflow.db.repo.Operator;
import com.ke.bella.workflow.db.tables.WorkflowNodeRun;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record21;
import org.jooq.Row21;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkflowNodeRunRecord extends UpdatableRecordImpl<WorkflowNodeRunRecord> implements Operator, Record21<Long, String, String, String, String, String, String, String, String, String, String, String, String, String, Long, Long, String, LocalDateTime, Long, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>workflow_node_run.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>workflow_node_run.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>workflow_node_run.tenant_id</code>.
     */
    public void setTenantId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>workflow_node_run.tenant_id</code>.
     */
    public String getTenantId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>workflow_node_run.workflow_id</code>.
     */
    public void setWorkflowId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>workflow_node_run.workflow_id</code>.
     */
    public String getWorkflowId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>workflow_node_run.workflow_run_id</code>.
     */
    public void setWorkflowRunId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>workflow_node_run.workflow_run_id</code>.
     */
    public String getWorkflowRunId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>workflow_node_run.node_id</code>.
     */
    public void setNodeId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>workflow_node_run.node_id</code>.
     */
    public String getNodeId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>workflow_node_run.node_type</code>.
     */
    public void setNodeType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>workflow_node_run.node_type</code>.
     */
    public String getNodeType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>workflow_node_run.title</code>.
     */
    public void setTitle(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>workflow_node_run.title</code>.
     */
    public String getTitle() {
        return (String) get(6);
    }

    /**
     * Setter for <code>workflow_node_run.inputs</code>.
     */
    public void setInputs(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>workflow_node_run.inputs</code>.
     */
    public String getInputs() {
        return (String) get(7);
    }

    /**
     * Setter for <code>workflow_node_run.outputs</code>.
     */
    public void setOutputs(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>workflow_node_run.outputs</code>.
     */
    public String getOutputs() {
        return (String) get(8);
    }

    /**
     * Setter for <code>workflow_node_run.error</code>.
     */
    public void setError(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>workflow_node_run.error</code>.
     */
    public String getError() {
        return (String) get(9);
    }

    /**
     * Setter for <code>workflow_node_run.process_data</code>.
     */
    public void setProcessData(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>workflow_node_run.process_data</code>.
     */
    public String getProcessData() {
        return (String) get(10);
    }

    /**
     * Setter for <code>workflow_node_run.notify_data</code>.
     */
    public void setNotifyData(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>workflow_node_run.notify_data</code>.
     */
    public String getNotifyData() {
        return (String) get(11);
    }

    /**
     * Setter for <code>workflow_node_run.actived_target_handles</code>.
     */
    public void setActivedTargetHandles(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>workflow_node_run.actived_target_handles</code>.
     */
    public String getActivedTargetHandles() {
        return (String) get(12);
    }

    /**
     * Setter for <code>workflow_node_run.status</code>.
     */
    public void setStatus(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>workflow_node_run.status</code>.
     */
    public String getStatus() {
        return (String) get(13);
    }

    /**
     * Setter for <code>workflow_node_run.elapsed_time</code>.
     */
    public void setElapsedTime(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>workflow_node_run.elapsed_time</code>.
     */
    public Long getElapsedTime() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>workflow_node_run.cuid</code>.
     */
    public void setCuid(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>workflow_node_run.cuid</code>.
     */
    public Long getCuid() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>workflow_node_run.cu_name</code>.
     */
    public void setCuName(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>workflow_node_run.cu_name</code>.
     */
    public String getCuName() {
        return (String) get(16);
    }

    /**
     * Setter for <code>workflow_node_run.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(17, value);
    }

    /**
     * Getter for <code>workflow_node_run.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(17);
    }

    /**
     * Setter for <code>workflow_node_run.muid</code>.
     */
    public void setMuid(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>workflow_node_run.muid</code>.
     */
    public Long getMuid() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>workflow_node_run.mu_name</code>.
     */
    public void setMuName(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>workflow_node_run.mu_name</code>.
     */
    public String getMuName() {
        return (String) get(19);
    }

    /**
     * Setter for <code>workflow_node_run.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(20, value);
    }

    /**
     * Getter for <code>workflow_node_run.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(20);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record21 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row21<Long, String, String, String, String, String, String, String, String, String, String, String, String, String, Long, Long, String, LocalDateTime, Long, String, LocalDateTime> fieldsRow() {
        return (Row21) super.fieldsRow();
    }

    @Override
    public Row21<Long, String, String, String, String, String, String, String, String, String, String, String, String, String, Long, Long, String, LocalDateTime, Long, String, LocalDateTime> valuesRow() {
        return (Row21) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return WorkflowNodeRun.WORKFLOW_NODE_RUN.ID;
    }

    @Override
    public Field<String> field2() {
        return WorkflowNodeRun.WORKFLOW_NODE_RUN.TENANT_ID;
    }

    @Override
    public Field<String> field3() {
        return WorkflowNodeRun.WORKFLOW_NODE_RUN.WORKFLOW_ID;
    }

    @Override
    public Field<String> field4() {
        return WorkflowNodeRun.WORKFLOW_NODE_RUN.WORKFLOW_RUN_ID;
    }

    @Override
    public Field<String> field5() {
        return WorkflowNodeRun.WORKFLOW_NODE_RUN.NODE_ID;
    }

    @Override
    public Field<String> field6() {
        return WorkflowNodeRun.WORKFLOW_NODE_RUN.NODE_TYPE;
    }

    @Override
    public Field<String> field7() {
        return WorkflowNodeRun.WORKFLOW_NODE_RUN.TITLE;
    }

    @Override
    public Field<String> field8() {
        return WorkflowNodeRun.WORKFLOW_NODE_RUN.INPUTS;
    }

    @Override
    public Field<String> field9() {
        return WorkflowNodeRun.WORKFLOW_NODE_RUN.OUTPUTS;
    }

    @Override
    public Field<String> field10() {
        return WorkflowNodeRun.WORKFLOW_NODE_RUN.ERROR;
    }

    @Override
    public Field<String> field11() {
        return WorkflowNodeRun.WORKFLOW_NODE_RUN.PROCESS_DATA;
    }

    @Override
    public Field<String> field12() {
        return WorkflowNodeRun.WORKFLOW_NODE_RUN.NOTIFY_DATA;
    }

    @Override
    public Field<String> field13() {
        return WorkflowNodeRun.WORKFLOW_NODE_RUN.ACTIVED_TARGET_HANDLES;
    }

    @Override
    public Field<String> field14() {
        return WorkflowNodeRun.WORKFLOW_NODE_RUN.STATUS;
    }

    @Override
    public Field<Long> field15() {
        return WorkflowNodeRun.WORKFLOW_NODE_RUN.ELAPSED_TIME;
    }

    @Override
    public Field<Long> field16() {
        return WorkflowNodeRun.WORKFLOW_NODE_RUN.CUID;
    }

    @Override
    public Field<String> field17() {
        return WorkflowNodeRun.WORKFLOW_NODE_RUN.CU_NAME;
    }

    @Override
    public Field<LocalDateTime> field18() {
        return WorkflowNodeRun.WORKFLOW_NODE_RUN.CTIME;
    }

    @Override
    public Field<Long> field19() {
        return WorkflowNodeRun.WORKFLOW_NODE_RUN.MUID;
    }

    @Override
    public Field<String> field20() {
        return WorkflowNodeRun.WORKFLOW_NODE_RUN.MU_NAME;
    }

    @Override
    public Field<LocalDateTime> field21() {
        return WorkflowNodeRun.WORKFLOW_NODE_RUN.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTenantId();
    }

    @Override
    public String component3() {
        return getWorkflowId();
    }

    @Override
    public String component4() {
        return getWorkflowRunId();
    }

    @Override
    public String component5() {
        return getNodeId();
    }

    @Override
    public String component6() {
        return getNodeType();
    }

    @Override
    public String component7() {
        return getTitle();
    }

    @Override
    public String component8() {
        return getInputs();
    }

    @Override
    public String component9() {
        return getOutputs();
    }

    @Override
    public String component10() {
        return getError();
    }

    @Override
    public String component11() {
        return getProcessData();
    }

    @Override
    public String component12() {
        return getNotifyData();
    }

    @Override
    public String component13() {
        return getActivedTargetHandles();
    }

    @Override
    public String component14() {
        return getStatus();
    }

    @Override
    public Long component15() {
        return getElapsedTime();
    }

    @Override
    public Long component16() {
        return getCuid();
    }

    @Override
    public String component17() {
        return getCuName();
    }

    @Override
    public LocalDateTime component18() {
        return getCtime();
    }

    @Override
    public Long component19() {
        return getMuid();
    }

    @Override
    public String component20() {
        return getMuName();
    }

    @Override
    public LocalDateTime component21() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTenantId();
    }

    @Override
    public String value3() {
        return getWorkflowId();
    }

    @Override
    public String value4() {
        return getWorkflowRunId();
    }

    @Override
    public String value5() {
        return getNodeId();
    }

    @Override
    public String value6() {
        return getNodeType();
    }

    @Override
    public String value7() {
        return getTitle();
    }

    @Override
    public String value8() {
        return getInputs();
    }

    @Override
    public String value9() {
        return getOutputs();
    }

    @Override
    public String value10() {
        return getError();
    }

    @Override
    public String value11() {
        return getProcessData();
    }

    @Override
    public String value12() {
        return getNotifyData();
    }

    @Override
    public String value13() {
        return getActivedTargetHandles();
    }

    @Override
    public String value14() {
        return getStatus();
    }

    @Override
    public Long value15() {
        return getElapsedTime();
    }

    @Override
    public Long value16() {
        return getCuid();
    }

    @Override
    public String value17() {
        return getCuName();
    }

    @Override
    public LocalDateTime value18() {
        return getCtime();
    }

    @Override
    public Long value19() {
        return getMuid();
    }

    @Override
    public String value20() {
        return getMuName();
    }

    @Override
    public LocalDateTime value21() {
        return getMtime();
    }

    @Override
    public WorkflowNodeRunRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public WorkflowNodeRunRecord value2(String value) {
        setTenantId(value);
        return this;
    }

    @Override
    public WorkflowNodeRunRecord value3(String value) {
        setWorkflowId(value);
        return this;
    }

    @Override
    public WorkflowNodeRunRecord value4(String value) {
        setWorkflowRunId(value);
        return this;
    }

    @Override
    public WorkflowNodeRunRecord value5(String value) {
        setNodeId(value);
        return this;
    }

    @Override
    public WorkflowNodeRunRecord value6(String value) {
        setNodeType(value);
        return this;
    }

    @Override
    public WorkflowNodeRunRecord value7(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public WorkflowNodeRunRecord value8(String value) {
        setInputs(value);
        return this;
    }

    @Override
    public WorkflowNodeRunRecord value9(String value) {
        setOutputs(value);
        return this;
    }

    @Override
    public WorkflowNodeRunRecord value10(String value) {
        setError(value);
        return this;
    }

    @Override
    public WorkflowNodeRunRecord value11(String value) {
        setProcessData(value);
        return this;
    }

    @Override
    public WorkflowNodeRunRecord value12(String value) {
        setNotifyData(value);
        return this;
    }

    @Override
    public WorkflowNodeRunRecord value13(String value) {
        setActivedTargetHandles(value);
        return this;
    }

    @Override
    public WorkflowNodeRunRecord value14(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public WorkflowNodeRunRecord value15(Long value) {
        setElapsedTime(value);
        return this;
    }

    @Override
    public WorkflowNodeRunRecord value16(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public WorkflowNodeRunRecord value17(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public WorkflowNodeRunRecord value18(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public WorkflowNodeRunRecord value19(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public WorkflowNodeRunRecord value20(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public WorkflowNodeRunRecord value21(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public WorkflowNodeRunRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, Long value15, Long value16, String value17, LocalDateTime value18, Long value19, String value20, LocalDateTime value21) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkflowNodeRunRecord
     */
    public WorkflowNodeRunRecord() {
        super(WorkflowNodeRun.WORKFLOW_NODE_RUN);
    }

    /**
     * Create a detached, initialised WorkflowNodeRunRecord
     */
    public WorkflowNodeRunRecord(Long id, String tenantId, String workflowId, String workflowRunId, String nodeId, String nodeType, String title, String inputs, String outputs, String error, String processData, String notifyData, String activedTargetHandles, String status, Long elapsedTime, Long cuid, String cuName, LocalDateTime ctime, Long muid, String muName, LocalDateTime mtime) {
        super(WorkflowNodeRun.WORKFLOW_NODE_RUN);

        setId(id);
        setTenantId(tenantId);
        setWorkflowId(workflowId);
        setWorkflowRunId(workflowRunId);
        setNodeId(nodeId);
        setNodeType(nodeType);
        setTitle(title);
        setInputs(inputs);
        setOutputs(outputs);
        setError(error);
        setProcessData(processData);
        setNotifyData(notifyData);
        setActivedTargetHandles(activedTargetHandles);
        setStatus(status);
        setElapsedTime(elapsedTime);
        setCuid(cuid);
        setCuName(cuName);
        setCtime(ctime);
        setMuid(muid);
        setMuName(muName);
        setMtime(mtime);
    }
}
