/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.workflow.db.tables.records;


import com.ke.bella.workflow.db.repo.Operator;
import com.ke.bella.workflow.db.tables.Workflow;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkflowRecord extends UpdatableRecordImpl<WorkflowRecord> implements Operator, Record11<Long, String, String, String, Long, Long, String, LocalDateTime, Long, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>workflow.id</code>. workflow配置自增主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>workflow.id</code>. workflow配置自增主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>workflow.tenant_id</code>. 租户id
     */
    public void setTenantId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>workflow.tenant_id</code>. 租户id
     */
    public String getTenantId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>workflow.workflow_id</code>.
     */
    public void setWorkflowId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>workflow.workflow_id</code>.
     */
    public String getWorkflowId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>workflow.graph</code>. 工作流DAG配置
     */
    public void setGraph(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>workflow.graph</code>. 工作流DAG配置
     */
    public String getGraph() {
        return (String) get(3);
    }

    /**
     * Setter for <code>workflow.version</code>. 工作流版本，0: draft, &gt;0 正式版时间戳
     */
    public void setVersion(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>workflow.version</code>. 工作流版本，0: draft, &gt;0 正式版时间戳
     */
    public Long getVersion() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>workflow.cuid</code>.
     */
    public void setCuid(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>workflow.cuid</code>.
     */
    public Long getCuid() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>workflow.cu_name</code>.
     */
    public void setCuName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>workflow.cu_name</code>.
     */
    public String getCuName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>workflow.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>workflow.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>workflow.muid</code>.
     */
    public void setMuid(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>workflow.muid</code>.
     */
    public Long getMuid() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>workflow.mu_name</code>.
     */
    public void setMuName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>workflow.mu_name</code>.
     */
    public String getMuName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>workflow.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>workflow.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, String, String, String, Long, Long, String, LocalDateTime, Long, String, LocalDateTime> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, String, String, String, Long, Long, String, LocalDateTime, Long, String, LocalDateTime> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Workflow.WORKFLOW.ID;
    }

    @Override
    public Field<String> field2() {
        return Workflow.WORKFLOW.TENANT_ID;
    }

    @Override
    public Field<String> field3() {
        return Workflow.WORKFLOW.WORKFLOW_ID;
    }

    @Override
    public Field<String> field4() {
        return Workflow.WORKFLOW.GRAPH;
    }

    @Override
    public Field<Long> field5() {
        return Workflow.WORKFLOW.VERSION;
    }

    @Override
    public Field<Long> field6() {
        return Workflow.WORKFLOW.CUID;
    }

    @Override
    public Field<String> field7() {
        return Workflow.WORKFLOW.CU_NAME;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Workflow.WORKFLOW.CTIME;
    }

    @Override
    public Field<Long> field9() {
        return Workflow.WORKFLOW.MUID;
    }

    @Override
    public Field<String> field10() {
        return Workflow.WORKFLOW.MU_NAME;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return Workflow.WORKFLOW.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTenantId();
    }

    @Override
    public String component3() {
        return getWorkflowId();
    }

    @Override
    public String component4() {
        return getGraph();
    }

    @Override
    public Long component5() {
        return getVersion();
    }

    @Override
    public Long component6() {
        return getCuid();
    }

    @Override
    public String component7() {
        return getCuName();
    }

    @Override
    public LocalDateTime component8() {
        return getCtime();
    }

    @Override
    public Long component9() {
        return getMuid();
    }

    @Override
    public String component10() {
        return getMuName();
    }

    @Override
    public LocalDateTime component11() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTenantId();
    }

    @Override
    public String value3() {
        return getWorkflowId();
    }

    @Override
    public String value4() {
        return getGraph();
    }

    @Override
    public Long value5() {
        return getVersion();
    }

    @Override
    public Long value6() {
        return getCuid();
    }

    @Override
    public String value7() {
        return getCuName();
    }

    @Override
    public LocalDateTime value8() {
        return getCtime();
    }

    @Override
    public Long value9() {
        return getMuid();
    }

    @Override
    public String value10() {
        return getMuName();
    }

    @Override
    public LocalDateTime value11() {
        return getMtime();
    }

    @Override
    public WorkflowRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public WorkflowRecord value2(String value) {
        setTenantId(value);
        return this;
    }

    @Override
    public WorkflowRecord value3(String value) {
        setWorkflowId(value);
        return this;
    }

    @Override
    public WorkflowRecord value4(String value) {
        setGraph(value);
        return this;
    }

    @Override
    public WorkflowRecord value5(Long value) {
        setVersion(value);
        return this;
    }

    @Override
    public WorkflowRecord value6(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public WorkflowRecord value7(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public WorkflowRecord value8(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public WorkflowRecord value9(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public WorkflowRecord value10(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public WorkflowRecord value11(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public WorkflowRecord values(Long value1, String value2, String value3, String value4, Long value5, Long value6, String value7, LocalDateTime value8, Long value9, String value10, LocalDateTime value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkflowRecord
     */
    public WorkflowRecord() {
        super(Workflow.WORKFLOW);
    }

    /**
     * Create a detached, initialised WorkflowRecord
     */
    public WorkflowRecord(Long id, String tenantId, String workflowId, String graph, Long version, Long cuid, String cuName, LocalDateTime ctime, Long muid, String muName, LocalDateTime mtime) {
        super(Workflow.WORKFLOW);

        setId(id);
        setTenantId(tenantId);
        setWorkflowId(workflowId);
        setGraph(graph);
        setVersion(version);
        setCuid(cuid);
        setCuName(cuName);
        setCtime(ctime);
        setMuid(muid);
        setMuName(muName);
        setMtime(mtime);
    }
}
