/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.workflow.db.tables.records;

import com.ke.bella.workflow.db.repo.Operator;
import com.ke.bella.workflow.db.tables.WorkflowAggregate;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkflowAggregateRecord extends UpdatableRecordImpl<WorkflowAggregateRecord> implements Operator,
        Record14<Long, String, String, String, String, String, Long, Long, Long, String, LocalDateTime, Long, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached WorkflowAggregateRecord
     */
    public WorkflowAggregateRecord() {
        super(WorkflowAggregate.WORKFLOW_AGGREGATE);
    }

    /**
     * Create a detached, initialised WorkflowAggregateRecord
     */
    public WorkflowAggregateRecord(Long id, String tenantId, String workflowId, String title, String desc, String graph, Long version,
            Long latestPublishVersion, Long cuid, String cuName, LocalDateTime ctime, Long muid, String muName, LocalDateTime mtime) {
        super(WorkflowAggregate.WORKFLOW_AGGREGATE);

        setId(id);
        setTenantId(tenantId);
        setWorkflowId(workflowId);
        setTitle(title);
        setDesc(desc);
        setGraph(graph);
        setVersion(version);
        setLatestPublishVersion(latestPublishVersion);
        setCuid(cuid);
        setCuName(cuName);
        setCtime(ctime);
        setMuid(muid);
        setMuName(muName);
        setMtime(mtime);
    }

    /**
     * Getter for <code>workflow_aggregate.id</code>. workflow配置自增主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>workflow_aggregate.id</code>. workflow配置自增主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>workflow_aggregate.tenant_id</code>. 租户id
     */
    public String getTenantId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>workflow_aggregate.tenant_id</code>. 租户id
     */
    public void setTenantId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>workflow_aggregate.workflow_id</code>.
     */
    public String getWorkflowId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>workflow_aggregate.workflow_id</code>.
     */
    public void setWorkflowId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>workflow_aggregate.title</code>.
     */
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>workflow_aggregate.title</code>.
     */
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>workflow_aggregate.desc</code>.
     */
    public String getDesc() {
        return (String) get(4);
    }

    /**
     * Setter for <code>workflow_aggregate.desc</code>.
     */
    public void setDesc(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>workflow_aggregate.graph</code>. 工作流DAG配置
     */
    public String getGraph() {
        return (String) get(5);
    }

    /**
     * Setter for <code>workflow_aggregate.graph</code>. 工作流DAG配置
     */
    public void setGraph(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>workflow_aggregate.version</code>. 工作流版本，0: draft, &gt;0
     * 正式版时间戳
     */
    public Long getVersion() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>workflow_aggregate.version</code>. 工作流版本，0: draft, &gt;0
     * 正式版时间戳
     */
    public void setVersion(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>workflow_aggregate.latest_publish_version</code>.
     * 工作流最新发布版本，0: draft, &gt;0 正式版时间戳
     */
    public Long getLatestPublishVersion() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>workflow_aggregate.latest_publish_version</code>.
     * 工作流最新发布版本，0: draft, &gt;0 正式版时间戳
     */
    public void setLatestPublishVersion(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>workflow_aggregate.cuid</code>.
     */
    public Long getCuid() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>workflow_aggregate.cuid</code>.
     */
    public void setCuid(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>workflow_aggregate.cu_name</code>.
     */
    public String getCuName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>workflow_aggregate.cu_name</code>.
     */
    public void setCuName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>workflow_aggregate.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>workflow_aggregate.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>workflow_aggregate.muid</code>.
     */
    public Long getMuid() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>workflow_aggregate.muid</code>.
     */
    public void setMuid(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>workflow_aggregate.mu_name</code>.
     */
    public String getMuName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>workflow_aggregate.mu_name</code>.
     */
    public void setMuName(String value) {
        set(12, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>workflow_aggregate.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>workflow_aggregate.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(13, value);
    }

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    @Override
    public Row14<Long, String, String, String, String, String, Long, Long, Long, String, LocalDateTime, Long, String, LocalDateTime> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Long, String, String, String, String, String, Long, Long, Long, String, LocalDateTime, Long, String, LocalDateTime> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return WorkflowAggregate.WORKFLOW_AGGREGATE.ID;
    }

    @Override
    public Field<String> field2() {
        return WorkflowAggregate.WORKFLOW_AGGREGATE.TENANT_ID;
    }

    @Override
    public Field<String> field3() {
        return WorkflowAggregate.WORKFLOW_AGGREGATE.WORKFLOW_ID;
    }

    @Override
    public Field<String> field4() {
        return WorkflowAggregate.WORKFLOW_AGGREGATE.TITLE;
    }

    @Override
    public Field<String> field5() {
        return WorkflowAggregate.WORKFLOW_AGGREGATE.DESC;
    }

    @Override
    public Field<String> field6() {
        return WorkflowAggregate.WORKFLOW_AGGREGATE.GRAPH;
    }

    @Override
    public Field<Long> field7() {
        return WorkflowAggregate.WORKFLOW_AGGREGATE.VERSION;
    }

    @Override
    public Field<Long> field8() {
        return WorkflowAggregate.WORKFLOW_AGGREGATE.LATEST_PUBLISH_VERSION;
    }

    @Override
    public Field<Long> field9() {
        return WorkflowAggregate.WORKFLOW_AGGREGATE.CUID;
    }

    @Override
    public Field<String> field10() {
        return WorkflowAggregate.WORKFLOW_AGGREGATE.CU_NAME;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return WorkflowAggregate.WORKFLOW_AGGREGATE.CTIME;
    }

    @Override
    public Field<Long> field12() {
        return WorkflowAggregate.WORKFLOW_AGGREGATE.MUID;
    }

    @Override
    public Field<String> field13() {
        return WorkflowAggregate.WORKFLOW_AGGREGATE.MU_NAME;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return WorkflowAggregate.WORKFLOW_AGGREGATE.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTenantId();
    }

    @Override
    public String component3() {
        return getWorkflowId();
    }

    @Override
    public String component4() {
        return getTitle();
    }

    @Override
    public String component5() {
        return getDesc();
    }

    @Override
    public String component6() {
        return getGraph();
    }

    @Override
    public Long component7() {
        return getVersion();
    }

    @Override
    public Long component8() {
        return getLatestPublishVersion();
    }

    @Override
    public Long component9() {
        return getCuid();
    }

    @Override
    public String component10() {
        return getCuName();
    }

    @Override
    public LocalDateTime component11() {
        return getCtime();
    }

    @Override
    public Long component12() {
        return getMuid();
    }

    @Override
    public String component13() {
        return getMuName();
    }

    @Override
    public LocalDateTime component14() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTenantId();
    }

    @Override
    public String value3() {
        return getWorkflowId();
    }

    @Override
    public String value4() {
        return getTitle();
    }

    @Override
    public String value5() {
        return getDesc();
    }

    @Override
    public String value6() {
        return getGraph();
    }

    @Override
    public Long value7() {
        return getVersion();
    }

    @Override
    public Long value8() {
        return getLatestPublishVersion();
    }

    @Override
    public Long value9() {
        return getCuid();
    }

    @Override
    public String value10() {
        return getCuName();
    }

    @Override
    public LocalDateTime value11() {
        return getCtime();
    }

    @Override
    public Long value12() {
        return getMuid();
    }

    @Override
    public String value13() {
        return getMuName();
    }

    @Override
    public LocalDateTime value14() {
        return getMtime();
    }

    @Override
    public WorkflowAggregateRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public WorkflowAggregateRecord value2(String value) {
        setTenantId(value);
        return this;
    }

    @Override
    public WorkflowAggregateRecord value3(String value) {
        setWorkflowId(value);
        return this;
    }

    @Override
    public WorkflowAggregateRecord value4(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public WorkflowAggregateRecord value5(String value) {
        setDesc(value);
        return this;
    }

    @Override
    public WorkflowAggregateRecord value6(String value) {
        setGraph(value);
        return this;
    }

    @Override
    public WorkflowAggregateRecord value7(Long value) {
        setVersion(value);
        return this;
    }

    @Override
    public WorkflowAggregateRecord value8(Long value) {
        setLatestPublishVersion(value);
        return this;
    }

    @Override
    public WorkflowAggregateRecord value9(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public WorkflowAggregateRecord value10(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public WorkflowAggregateRecord value11(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public WorkflowAggregateRecord value12(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public WorkflowAggregateRecord value13(String value) {
        setMuName(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public WorkflowAggregateRecord value14(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public WorkflowAggregateRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, Long value7,
            Long value8, Long value9, String value10, LocalDateTime value11, Long value12, String value13, LocalDateTime value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }
}
