/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.workflow.db.tables.records;


import com.ke.bella.workflow.db.repo.Operator;
import com.ke.bella.workflow.db.tables.WorkflowRun;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record20;
import org.jooq.Row20;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkflowRunRecord extends UpdatableRecordImpl<WorkflowRunRecord> implements Operator, Record20<Long, String, String, Long, String, String, String, String, String, String, String, String, Integer, Long, String, LocalDateTime, Long, String, LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>workflow_run.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>workflow_run.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>workflow_run.tenant_id</code>.
     */
    public void setTenantId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>workflow_run.tenant_id</code>.
     */
    public String getTenantId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>workflow_run.workflow_id</code>.
     */
    public void setWorkflowId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>workflow_run.workflow_id</code>.
     */
    public String getWorkflowId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>workflow_run.workflow_version</code>.
     */
    public void setWorkflowVersion(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>workflow_run.workflow_version</code>.
     */
    public Long getWorkflowVersion() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>workflow_run.workflow_run_id</code>.
     */
    public void setWorkflowRunId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>workflow_run.workflow_run_id</code>.
     */
    public String getWorkflowRunId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>workflow_run.workflow_run_sharding_key</code>.
     */
    public void setWorkflowRunShardingKey(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>workflow_run.workflow_run_sharding_key</code>.
     */
    public String getWorkflowRunShardingKey() {
        return (String) get(5);
    }

    /**
     * Setter for <code>workflow_run.trigger_from</code>. 工作流触发来源：
DEBUG
DEBUG_NODE
API


     */
    public void setTriggerFrom(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>workflow_run.trigger_from</code>. 工作流触发来源：
DEBUG
DEBUG_NODE
API


     */
    public String getTriggerFrom() {
        return (String) get(6);
    }

    /**
     * Setter for <code>workflow_run.inputs</code>.
     */
    public void setInputs(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>workflow_run.inputs</code>.
     */
    public String getInputs() {
        return (String) get(7);
    }

    /**
     * Setter for <code>workflow_run.outputs</code>. 最后一个节点的输出
     */
    public void setOutputs(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>workflow_run.outputs</code>. 最后一个节点的输出
     */
    public String getOutputs() {
        return (String) get(8);
    }

    /**
     * Setter for <code>workflow_run.status</code>.     
    INIT=‘init’
    RUNNING = 'running'
    SUCCEEDED = 'succeeded'
    FAILED = 'failed'
    STOPPED = 'stopped'

     */
    public void setStatus(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>workflow_run.status</code>.     
    INIT=‘init’
    RUNNING = 'running'
    SUCCEEDED = 'succeeded'
    FAILED = 'failed'
    STOPPED = 'stopped'

     */
    public String getStatus() {
        return (String) get(9);
    }

    /**
     * Setter for <code>workflow_run.error</code>.
     */
    public void setError(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>workflow_run.error</code>.
     */
    public String getError() {
        return (String) get(10);
    }

    /**
     * Setter for <code>workflow_run.callback_url</code>.
     */
    public void setCallbackUrl(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>workflow_run.callback_url</code>.
     */
    public String getCallbackUrl() {
        return (String) get(11);
    }

    /**
     * Setter for <code>workflow_run.callback_status</code>.
     */
    public void setCallbackStatus(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>workflow_run.callback_status</code>.
     */
    public Integer getCallbackStatus() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>workflow_run.cuid</code>.
     */
    public void setCuid(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>workflow_run.cuid</code>.
     */
    public Long getCuid() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>workflow_run.cu_name</code>.
     */
    public void setCuName(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>workflow_run.cu_name</code>.
     */
    public String getCuName() {
        return (String) get(14);
    }

    /**
     * Setter for <code>workflow_run.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>workflow_run.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>workflow_run.muid</code>.
     */
    public void setMuid(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>workflow_run.muid</code>.
     */
    public Long getMuid() {
        return (Long) get(16);
    }

    /**
     * Setter for <code>workflow_run.mu_name</code>.
     */
    public void setMuName(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>workflow_run.mu_name</code>.
     */
    public String getMuName() {
        return (String) get(17);
    }

    /**
     * Setter for <code>workflow_run.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(18, value);
    }

    /**
     * Getter for <code>workflow_run.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(18);
    }

    /**
     * Setter for <code>workflow_run.response_mode</code>.
     */
    public void setResponseMode(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>workflow_run.response_mode</code>.
     */
    public String getResponseMode() {
        return (String) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record20 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row20<Long, String, String, Long, String, String, String, String, String, String, String, String, Integer, Long, String, LocalDateTime, Long, String, LocalDateTime, String> fieldsRow() {
        return (Row20) super.fieldsRow();
    }

    @Override
    public Row20<Long, String, String, Long, String, String, String, String, String, String, String, String, Integer, Long, String, LocalDateTime, Long, String, LocalDateTime, String> valuesRow() {
        return (Row20) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return WorkflowRun.WORKFLOW_RUN.ID;
    }

    @Override
    public Field<String> field2() {
        return WorkflowRun.WORKFLOW_RUN.TENANT_ID;
    }

    @Override
    public Field<String> field3() {
        return WorkflowRun.WORKFLOW_RUN.WORKFLOW_ID;
    }

    @Override
    public Field<Long> field4() {
        return WorkflowRun.WORKFLOW_RUN.WORKFLOW_VERSION;
    }

    @Override
    public Field<String> field5() {
        return WorkflowRun.WORKFLOW_RUN.WORKFLOW_RUN_ID;
    }

    @Override
    public Field<String> field6() {
        return WorkflowRun.WORKFLOW_RUN.WORKFLOW_RUN_SHARDING_KEY;
    }

    @Override
    public Field<String> field7() {
        return WorkflowRun.WORKFLOW_RUN.TRIGGER_FROM;
    }

    @Override
    public Field<String> field8() {
        return WorkflowRun.WORKFLOW_RUN.INPUTS;
    }

    @Override
    public Field<String> field9() {
        return WorkflowRun.WORKFLOW_RUN.OUTPUTS;
    }

    @Override
    public Field<String> field10() {
        return WorkflowRun.WORKFLOW_RUN.STATUS;
    }

    @Override
    public Field<String> field11() {
        return WorkflowRun.WORKFLOW_RUN.ERROR;
    }

    @Override
    public Field<String> field12() {
        return WorkflowRun.WORKFLOW_RUN.CALLBACK_URL;
    }

    @Override
    public Field<Integer> field13() {
        return WorkflowRun.WORKFLOW_RUN.CALLBACK_STATUS;
    }

    @Override
    public Field<Long> field14() {
        return WorkflowRun.WORKFLOW_RUN.CUID;
    }

    @Override
    public Field<String> field15() {
        return WorkflowRun.WORKFLOW_RUN.CU_NAME;
    }

    @Override
    public Field<LocalDateTime> field16() {
        return WorkflowRun.WORKFLOW_RUN.CTIME;
    }

    @Override
    public Field<Long> field17() {
        return WorkflowRun.WORKFLOW_RUN.MUID;
    }

    @Override
    public Field<String> field18() {
        return WorkflowRun.WORKFLOW_RUN.MU_NAME;
    }

    @Override
    public Field<LocalDateTime> field19() {
        return WorkflowRun.WORKFLOW_RUN.MTIME;
    }

    @Override
    public Field<String> field20() {
        return WorkflowRun.WORKFLOW_RUN.RESPONSE_MODE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTenantId();
    }

    @Override
    public String component3() {
        return getWorkflowId();
    }

    @Override
    public Long component4() {
        return getWorkflowVersion();
    }

    @Override
    public String component5() {
        return getWorkflowRunId();
    }

    @Override
    public String component6() {
        return getWorkflowRunShardingKey();
    }

    @Override
    public String component7() {
        return getTriggerFrom();
    }

    @Override
    public String component8() {
        return getInputs();
    }

    @Override
    public String component9() {
        return getOutputs();
    }

    @Override
    public String component10() {
        return getStatus();
    }

    @Override
    public String component11() {
        return getError();
    }

    @Override
    public String component12() {
        return getCallbackUrl();
    }

    @Override
    public Integer component13() {
        return getCallbackStatus();
    }

    @Override
    public Long component14() {
        return getCuid();
    }

    @Override
    public String component15() {
        return getCuName();
    }

    @Override
    public LocalDateTime component16() {
        return getCtime();
    }

    @Override
    public Long component17() {
        return getMuid();
    }

    @Override
    public String component18() {
        return getMuName();
    }

    @Override
    public LocalDateTime component19() {
        return getMtime();
    }

    @Override
    public String component20() {
        return getResponseMode();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTenantId();
    }

    @Override
    public String value3() {
        return getWorkflowId();
    }

    @Override
    public Long value4() {
        return getWorkflowVersion();
    }

    @Override
    public String value5() {
        return getWorkflowRunId();
    }

    @Override
    public String value6() {
        return getWorkflowRunShardingKey();
    }

    @Override
    public String value7() {
        return getTriggerFrom();
    }

    @Override
    public String value8() {
        return getInputs();
    }

    @Override
    public String value9() {
        return getOutputs();
    }

    @Override
    public String value10() {
        return getStatus();
    }

    @Override
    public String value11() {
        return getError();
    }

    @Override
    public String value12() {
        return getCallbackUrl();
    }

    @Override
    public Integer value13() {
        return getCallbackStatus();
    }

    @Override
    public Long value14() {
        return getCuid();
    }

    @Override
    public String value15() {
        return getCuName();
    }

    @Override
    public LocalDateTime value16() {
        return getCtime();
    }

    @Override
    public Long value17() {
        return getMuid();
    }

    @Override
    public String value18() {
        return getMuName();
    }

    @Override
    public LocalDateTime value19() {
        return getMtime();
    }

    @Override
    public String value20() {
        return getResponseMode();
    }

    @Override
    public WorkflowRunRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public WorkflowRunRecord value2(String value) {
        setTenantId(value);
        return this;
    }

    @Override
    public WorkflowRunRecord value3(String value) {
        setWorkflowId(value);
        return this;
    }

    @Override
    public WorkflowRunRecord value4(Long value) {
        setWorkflowVersion(value);
        return this;
    }

    @Override
    public WorkflowRunRecord value5(String value) {
        setWorkflowRunId(value);
        return this;
    }

    @Override
    public WorkflowRunRecord value6(String value) {
        setWorkflowRunShardingKey(value);
        return this;
    }

    @Override
    public WorkflowRunRecord value7(String value) {
        setTriggerFrom(value);
        return this;
    }

    @Override
    public WorkflowRunRecord value8(String value) {
        setInputs(value);
        return this;
    }

    @Override
    public WorkflowRunRecord value9(String value) {
        setOutputs(value);
        return this;
    }

    @Override
    public WorkflowRunRecord value10(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public WorkflowRunRecord value11(String value) {
        setError(value);
        return this;
    }

    @Override
    public WorkflowRunRecord value12(String value) {
        setCallbackUrl(value);
        return this;
    }

    @Override
    public WorkflowRunRecord value13(Integer value) {
        setCallbackStatus(value);
        return this;
    }

    @Override
    public WorkflowRunRecord value14(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public WorkflowRunRecord value15(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public WorkflowRunRecord value16(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public WorkflowRunRecord value17(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public WorkflowRunRecord value18(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public WorkflowRunRecord value19(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public WorkflowRunRecord value20(String value) {
        setResponseMode(value);
        return this;
    }

    @Override
    public WorkflowRunRecord values(Long value1, String value2, String value3, Long value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, Integer value13, Long value14, String value15, LocalDateTime value16, Long value17, String value18, LocalDateTime value19, String value20) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkflowRunRecord
     */
    public WorkflowRunRecord() {
        super(WorkflowRun.WORKFLOW_RUN);
    }

    /**
     * Create a detached, initialised WorkflowRunRecord
     */
    public WorkflowRunRecord(Long id, String tenantId, String workflowId, Long workflowVersion, String workflowRunId, String workflowRunShardingKey, String triggerFrom, String inputs, String outputs, String status, String error, String callbackUrl, Integer callbackStatus, Long cuid, String cuName, LocalDateTime ctime, Long muid, String muName, LocalDateTime mtime, String responseMode) {
        super(WorkflowRun.WORKFLOW_RUN);

        setId(id);
        setTenantId(tenantId);
        setWorkflowId(workflowId);
        setWorkflowVersion(workflowVersion);
        setWorkflowRunId(workflowRunId);
        setWorkflowRunShardingKey(workflowRunShardingKey);
        setTriggerFrom(triggerFrom);
        setInputs(inputs);
        setOutputs(outputs);
        setStatus(status);
        setError(error);
        setCallbackUrl(callbackUrl);
        setCallbackStatus(callbackStatus);
        setCuid(cuid);
        setCuName(cuName);
        setCtime(ctime);
        setMuid(muid);
        setMuName(muName);
        setMtime(mtime);
        setResponseMode(responseMode);
    }
}
