#-------------------------------------------------------
# 服务全局配置文件
#-------------------------------------------------------
spring:
  application:
    name: bella-workflow
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_POOL_MASTER_URL}
    username: ${DATASOURCE_POOL_MASTER_USERNAME}
    password: ${DATASOURCE_POOL_MASTER_PASSWORD}
    hikari:
      minimum-idle: 50
      maximum-pool-size: 200
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

bella:
  server:
    initializer:
      enabled: true
  openapiHost: ${BELLA_OPENAPI_HOST:https://example.com}
  apiBase: ${BELLA_API_BASE:https://example.com/v1/}
  openApiBase: ${BELLA_OPEN_API_BASE:https://example.com/v1/}
  toolApiBase: ${BELLA_TOOL_API_BASE:http://example.com}
  boreApiBase: ${BELLA_TOOL_API_BASE:http://example.com}
  codeSandboxApiBase: ${BELLA_CODE_SANDBOX_API_BASE:https://example.com/v2/}
  maxEexMemoryAlloc: ${BELLA_MAX_EX_MEMORY_ALLOC:209715200}
  workflow:
    sandbox:
      groovy: false
  login:
    # 本地环境去掉 bella.login.type 即可关闭登录的身份校验
    type: cas
  session:
    cookie-name: bella_workflow_sessionId
    max-inactive-interval: 60
    cookie-max-age: -1
    cookie-domain: ke.com
    cookie-context-path: /
  cas:
    logoutUri: /console/api/logout
    client-support: true
  task:
    threadNums: 1000
app:
  id: bella-workflow
apollo:
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: application
  property:
    order:
      enabled: true
  cluster: default
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
