#-------------------------------------------------------
# PREVIEW环境配置区域
#-------------------------------------------------------
logging:
  level:
    root: INFO
    druid: INFO
    executableSql: INFO
    workflowRun: INFO
    org:
      springframework: INFO
      jooq: DEBUG
bella:
  workflow:
    hosts: example.com,example.com
    domain: http://example.com
    trigger:
      callback-path: /v1/workflow/trigger/callback
    run-path: /v1/workflow/run
    redis:
      host: 0.0.0.0
      port: 6379
      password: bella123
    files-upload-configs: '{"file_size_limit":512,"batch_count_limit":5,"image_file_size_limit":512,"video_file_size_limit":100,"audio_file_size_limit":100,"workflow_file_upload_limit":10}'
    run-log:
      elasticsearch:
        index: workflow_run_log_*
        hosts: example.com:9200,example.com:9200,example.com:9200
        username: bella_workflow
        password: eKXwhnSz2l
  knowledge-file:
    search: http://example.com/api/v1/knowledge/searchNew/forWorkflow
  cas:
    server-url-prefix: http://example.com/
    server-login-url: https://example.com/login
    client-host: https://example.com
    client-index-url: https://example.com/

spring:
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
      resolve-lazily: true
  redis:
    host: redis.example.com
    port: 14312
    password: bella123

s3:
  ak: bella123
  sk: bella123
  endpoint: https://example.com
  bucket: bella-workflow
  root: states
server:
  tomcat:
    max-swallow-size: -1
apollo:
  meta: http://example.com
