#-------------------------------------------------------
# TEST环境配置区域
#-------------------------------------------------------
logging:
  level:
    root: INFO
    druid: INFO
    executableSql: INFO
    org:
      springframework: INFO
      jooq: DEBUG

bella:
  workflow:
    hosts: localhost:8080,example.com,localhost:8083
    domain: http://example.com
    trigger:
      callback-path: /v1/workflow/trigger/callback
    run-path: /v1/workflow/run
    sandbox:
      groovy: true
    redis:
      host: 0.0.0.0
      port: 6379
      password: scaks3askjdh
    files-upload-configs: '{"file_size_limit":512,"batch_count_limit":5,"image_file_size_limit":512,"video_file_size_limit":100,"audio_file_size_limit":100,"workflow_file_upload_limit":10}'
    run-log:
      elasticsearch:
        index: workflow_run_log_test_*
        hosts: 0.0.0.0:9200,0.0.0.0:9200,0.0.0.0:9200
        username:
        password:
  knowledge-file:
    search: http://example.com/api/v1/knowledge/searchNew/forWorkflow
  session:
    cookie-domain: example.com
  cas:
    server-url-prefix: https://example.com/
    server-login-url: https://example.com/login
    client-host: http://example.com
    client-index-url: http://example.com/
  job-queue:
    url: http://example.com
    worker:
      enabled: false
      endpoint: /v1/workflow/run
      queueName: insight-offline-20250305

spring:
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
      resolve-lazily: true
  redis:
    host: redis.example.com
    port: 10373
    password: bella123
#    host: localhost
#    port: 6379

s3:
  ak: bella123
  sk: bella123
  endpoint: https://example.com
  bucket: bella-workflow
  root: test-states
server:
  tomcat:
    max-swallow-size: -1
apollo:
  meta: http://example.com
