/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.workflow.db;


import com.ke.bella.workflow.db.tables.Tenants;
import com.ke.bella.workflow.db.tables.WorkflowNodeRuns;
import com.ke.bella.workflow.db.tables.WorkflowRuns;
import com.ke.bella.workflow.db.tables.Workflows;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>tenants</code>.
     */
    public final Tenants TENANTS = Tenants.TENANTS;

    /**
     * The table <code>workflow_node_runs</code>.
     */
    public final WorkflowNodeRuns WORKFLOW_NODE_RUNS = WorkflowNodeRuns.WORKFLOW_NODE_RUNS;

    /**
     * The table <code>workflow_runs</code>.
     */
    public final WorkflowRuns WORKFLOW_RUNS = WorkflowRuns.WORKFLOW_RUNS;

    /**
     * The table <code>workflows</code>.
     */
    public final Workflows WORKFLOWS = Workflows.WORKFLOWS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Tenants.TENANTS,
            WorkflowNodeRuns.WORKFLOW_NODE_RUNS,
            WorkflowRuns.WORKFLOW_RUNS,
            Workflows.WORKFLOWS);
    }
}
