/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.workflow.db;


import com.ke.bella.workflow.db.tables.WorkflowNodeRuns;
import com.ke.bella.workflow.db.tables.WorkflowRuns;
import com.ke.bella.workflow.db.tables.Workflows;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index WORKFLOWS_IDX_CUID_TIME = Internal.createIndex(DSL.name("idx_cuid_time"), Workflows.WORKFLOWS, new OrderField[] { Workflows.WORKFLOWS.CUID, Workflows.WORKFLOWS.CTIME }, false);
    public static final Index WORKFLOW_RUNS_IDX_TENANT_ID = Internal.createIndex(DSL.name("idx_tenant_id"), WorkflowRuns.WORKFLOW_RUNS, new OrderField[] { WorkflowRuns.WORKFLOW_RUNS.TENANT_ID, WorkflowRuns.WORKFLOW_RUNS.CTIME }, false);
    public static final Index WORKFLOWS_IDX_TENANT_ID = Internal.createIndex(DSL.name("idx_tenant_id"), Workflows.WORKFLOWS, new OrderField[] { Workflows.WORKFLOWS.TENANT_ID, Workflows.WORKFLOWS.CUID, Workflows.WORKFLOWS.MTIME }, false);
    public static final Index WORKFLOW_NODE_RUNS_IDX_WORKFLOW_ID = Internal.createIndex(DSL.name("idx_workflow_id"), WorkflowNodeRuns.WORKFLOW_NODE_RUNS, new OrderField[] { WorkflowNodeRuns.WORKFLOW_NODE_RUNS.WORKFLOW_ID, WorkflowNodeRuns.WORKFLOW_NODE_RUNS.CTIME, WorkflowNodeRuns.WORKFLOW_NODE_RUNS.STATUS }, false);
    public static final Index WORKFLOW_RUNS_IDX_WORKFLOW_ID = Internal.createIndex(DSL.name("idx_workflow_id"), WorkflowRuns.WORKFLOW_RUNS, new OrderField[] { WorkflowRuns.WORKFLOW_RUNS.WORKFLOW_ID, WorkflowRuns.WORKFLOW_RUNS.CTIME, WorkflowRuns.WORKFLOW_RUNS.STATUS }, false);
    public static final Index WORKFLOW_NODE_RUNS_IDX_WORKFLOW_RUNID = Internal.createIndex(DSL.name("idx_workflow_runid"), WorkflowNodeRuns.WORKFLOW_NODE_RUNS, new OrderField[] { WorkflowNodeRuns.WORKFLOW_NODE_RUNS.WORKFLOW_RUN_ID, WorkflowNodeRuns.WORKFLOW_NODE_RUNS.NODE_ID }, false);
}
