/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.workflow.db;


import com.ke.bella.workflow.db.tables.Tenants;
import com.ke.bella.workflow.db.tables.WorkflowNodeRuns;
import com.ke.bella.workflow.db.tables.WorkflowRuns;
import com.ke.bella.workflow.db.tables.Workflows;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>tenants</code>.
     */
    public static final Tenants TENANTS = Tenants.TENANTS;

    /**
     * The table <code>workflow_node_runs</code>.
     */
    public static final WorkflowNodeRuns WORKFLOW_NODE_RUNS = WorkflowNodeRuns.WORKFLOW_NODE_RUNS;

    /**
     * The table <code>workflow_runs</code>.
     */
    public static final WorkflowRuns WORKFLOW_RUNS = WorkflowRuns.WORKFLOW_RUNS;

    /**
     * The table <code>workflows</code>.
     */
    public static final Workflows WORKFLOWS = Workflows.WORKFLOWS;
}
