/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.workflow.db.tables;


import com.ke.bella.workflow.db.DefaultSchema;
import com.ke.bella.workflow.db.Indexes;
import com.ke.bella.workflow.db.Keys;
import com.ke.bella.workflow.db.tables.records.RdbDatasourceRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row18;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RdbDatasource extends TableImpl<RdbDatasourceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rdb_datasource</code>
     */
    public static final RdbDatasource RDB_DATASOURCE = new RdbDatasource();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RdbDatasourceRecord> getRecordType() {
        return RdbDatasourceRecord.class;
    }

    /**
     * The column <code>rdb_datasource.id</code>.
     */
    public final TableField<RdbDatasourceRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>rdb_datasource.tenant_id</code>. 租户ID
     */
    public final TableField<RdbDatasourceRecord, String> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.VARCHAR(64).nullable(false), this, "租户ID");

    /**
     * The column <code>rdb_datasource.datasource_id</code>.
     */
    public final TableField<RdbDatasourceRecord, String> DATASOURCE_ID = createField(DSL.name("datasource_id"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>rdb_datasource.space_code</code>.
     */
    public final TableField<RdbDatasourceRecord, String> SPACE_CODE = createField(DSL.name("space_code"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>rdb_datasource.db_type</code>. mysql, postgresql
     */
    public final TableField<RdbDatasourceRecord, String> DB_TYPE = createField(DSL.name("db_type"), SQLDataType.VARCHAR(32).nullable(false), this, "mysql, postgresql");

    /**
     * The column <code>rdb_datasource.host</code>. 主机
host:port
     */
    public final TableField<RdbDatasourceRecord, String> HOST = createField(DSL.name("host"), SQLDataType.VARCHAR(512).nullable(false), this, "主机\nhost:port");

    /**
     * The column <code>rdb_datasource.port</code>. 端口
     */
    public final TableField<RdbDatasourceRecord, Integer> PORT = createField(DSL.name("port"), SQLDataType.INTEGER.nullable(false), this, "端口");

    /**
     * The column <code>rdb_datasource.db</code>. 默认数据库
     */
    public final TableField<RdbDatasourceRecord, String> DB = createField(DSL.name("db"), SQLDataType.VARCHAR(255).nullable(false), this, "默认数据库");

    /**
     * The column <code>rdb_datasource.user</code>. 用户名
     */
    public final TableField<RdbDatasourceRecord, String> USER = createField(DSL.name("user"), SQLDataType.VARCHAR(255).nullable(false), this, "用户名");

    /**
     * The column <code>rdb_datasource.password</code>. 密码
     */
    public final TableField<RdbDatasourceRecord, String> PASSWORD = createField(DSL.name("password"), SQLDataType.VARCHAR(255).nullable(false), this, "密码");

    /**
     * The column <code>rdb_datasource.params</code>. 其他参数
     */
    public final TableField<RdbDatasourceRecord, String> PARAMS = createField(DSL.name("params"), SQLDataType.VARCHAR(1024).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "其他参数");

    /**
     * The column <code>rdb_datasource.status</code>. 数据源状态
-1: 无笑
0: 生效
     */
    public final TableField<RdbDatasourceRecord, Integer> STATUS = createField(DSL.name("status"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "数据源状态\n-1: 无笑\n0: 生效");

    /**
     * The column <code>rdb_datasource.cuid</code>.
     */
    public final TableField<RdbDatasourceRecord, Long> CUID = createField(DSL.name("cuid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>rdb_datasource.muid</code>.
     */
    public final TableField<RdbDatasourceRecord, Long> MUID = createField(DSL.name("muid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>rdb_datasource.ctime</code>.
     */
    public final TableField<RdbDatasourceRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>rdb_datasource.mtime</code>.
     */
    public final TableField<RdbDatasourceRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>rdb_datasource.cu_name</code>.
     */
    public final TableField<RdbDatasourceRecord, String> CU_NAME = createField(DSL.name("cu_name"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>rdb_datasource.mu_name</code>.
     */
    public final TableField<RdbDatasourceRecord, String> MU_NAME = createField(DSL.name("mu_name"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    private RdbDatasource(Name alias, Table<RdbDatasourceRecord> aliased) {
        this(alias, aliased, null);
    }

    private RdbDatasource(Name alias, Table<RdbDatasourceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>rdb_datasource</code> table reference
     */
    public RdbDatasource(String alias) {
        this(DSL.name(alias), RDB_DATASOURCE);
    }

    /**
     * Create an aliased <code>rdb_datasource</code> table reference
     */
    public RdbDatasource(Name alias) {
        this(alias, RDB_DATASOURCE);
    }

    /**
     * Create a <code>rdb_datasource</code> table reference
     */
    public RdbDatasource() {
        this(DSL.name("rdb_datasource"), null);
    }

    public <O extends Record> RdbDatasource(Table<O> child, ForeignKey<O, RdbDatasourceRecord> key) {
        super(child, key, RDB_DATASOURCE);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RDB_DATASOURCE_IDX_T_SPACE_TOPIC);
    }

    @Override
    public Identity<RdbDatasourceRecord, Long> getIdentity() {
        return (Identity<RdbDatasourceRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<RdbDatasourceRecord> getPrimaryKey() {
        return Keys.KEY_RDB_DATASOURCE_PRIMARY;
    }

    @Override
    public List<UniqueKey<RdbDatasourceRecord>> getKeys() {
        return Arrays.<UniqueKey<RdbDatasourceRecord>>asList(Keys.KEY_RDB_DATASOURCE_PRIMARY, Keys.KEY_RDB_DATASOURCE_IDX_ID);
    }

    @Override
    public RdbDatasource as(String alias) {
        return new RdbDatasource(DSL.name(alias), this);
    }

    @Override
    public RdbDatasource as(Name alias) {
        return new RdbDatasource(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RdbDatasource rename(String name) {
        return new RdbDatasource(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RdbDatasource rename(Name name) {
        return new RdbDatasource(name, null);
    }

    // -------------------------------------------------------------------------
    // Row18 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row18<Long, String, String, String, String, String, Integer, String, String, String, String, Integer, Long, Long, LocalDateTime, LocalDateTime, String, String> fieldsRow() {
        return (Row18) super.fieldsRow();
    }
}
