/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.workflow.db.tables;


import com.ke.bella.workflow.db.DefaultSchema;
import com.ke.bella.workflow.db.Indexes;
import com.ke.bella.workflow.db.Keys;
import com.ke.bella.workflow.db.tables.records.WorkflowRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row14;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Workflow extends TableImpl<WorkflowRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>workflow</code>
     */
    public static final Workflow WORKFLOW = new Workflow();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WorkflowRecord> getRecordType() {
        return WorkflowRecord.class;
    }

    /**
     * The column <code>workflow.id</code>. workflow配置自增主键
     */
    public final TableField<WorkflowRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "workflow配置自增主键");

    /**
     * The column <code>workflow.tenant_id</code>. 租户id
     */
    public final TableField<WorkflowRecord, String> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.VARCHAR(64).nullable(false), this, "租户id");

    /**
     * The column <code>workflow.workflow_id</code>.
     */
    public final TableField<WorkflowRecord, String> WORKFLOW_ID = createField(DSL.name("workflow_id"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>workflow.title</code>.
     */
    public final TableField<WorkflowRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>workflow.mode</code>.
     */
    public final TableField<WorkflowRecord, String> MODE = createField(DSL.name("mode"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("workflow", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>workflow.desc</code>.
     */
    public final TableField<WorkflowRecord, String> DESC = createField(DSL.name("desc"), SQLDataType.VARCHAR(1024).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>workflow.graph</code>. 工作流DAG配置
     */
    public final TableField<WorkflowRecord, String> GRAPH = createField(DSL.name("graph"), SQLDataType.CLOB.nullable(false), this, "工作流DAG配置");

    /**
     * The column <code>workflow.version</code>. 工作流版本，0: draft, &gt;0 正式版时间戳
     */
    public final TableField<WorkflowRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "工作流版本，0: draft, >0 正式版时间戳");

    /**
     * The column <code>workflow.cuid</code>.
     */
    public final TableField<WorkflowRecord, Long> CUID = createField(DSL.name("cuid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>workflow.cu_name</code>.
     */
    public final TableField<WorkflowRecord, String> CU_NAME = createField(DSL.name("cu_name"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>workflow.ctime</code>.
     */
    public final TableField<WorkflowRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>workflow.muid</code>.
     */
    public final TableField<WorkflowRecord, Long> MUID = createField(DSL.name("muid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>workflow.mu_name</code>.
     */
    public final TableField<WorkflowRecord, String> MU_NAME = createField(DSL.name("mu_name"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>workflow.mtime</code>.
     */
    public final TableField<WorkflowRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private Workflow(Name alias, Table<WorkflowRecord> aliased) {
        this(alias, aliased, null);
    }

    private Workflow(Name alias, Table<WorkflowRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>workflow</code> table reference
     */
    public Workflow(String alias) {
        this(DSL.name(alias), WORKFLOW);
    }

    /**
     * Create an aliased <code>workflow</code> table reference
     */
    public Workflow(Name alias) {
        this(alias, WORKFLOW);
    }

    /**
     * Create a <code>workflow</code> table reference
     */
    public Workflow() {
        this(DSL.name("workflow"), null);
    }

    public <O extends Record> Workflow(Table<O> child, ForeignKey<O, WorkflowRecord> key) {
        super(child, key, WORKFLOW);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.WORKFLOW_IDX_CUID_TIME);
    }

    @Override
    public Identity<WorkflowRecord, Long> getIdentity() {
        return (Identity<WorkflowRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<WorkflowRecord> getPrimaryKey() {
        return Keys.KEY_WORKFLOW_PRIMARY;
    }

    @Override
    public List<UniqueKey<WorkflowRecord>> getKeys() {
        return Arrays.<UniqueKey<WorkflowRecord>>asList(Keys.KEY_WORKFLOW_PRIMARY, Keys.KEY_WORKFLOW_IDX_TENANT_ID);
    }

    @Override
    public Workflow as(String alias) {
        return new Workflow(DSL.name(alias), this);
    }

    @Override
    public Workflow as(Name alias) {
        return new Workflow(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Workflow rename(String name) {
        return new Workflow(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Workflow rename(Name name) {
        return new Workflow(name, null);
    }

    // -------------------------------------------------------------------------
    // Row14 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, String, String, String, String, String, String, Long, Long, String, LocalDateTime, Long, String, LocalDateTime> fieldsRow() {
        return (Row14) super.fieldsRow();
    }
}
