/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.workflow.db.tables.records;


import com.ke.bella.workflow.db.repo.Operator;
import com.ke.bella.workflow.db.tables.RedisDatasource;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RedisDatasourceRecord extends UpdatableRecordImpl<RedisDatasourceRecord> implements Operator, Record16<Long, String, String, String, String, Integer, Integer, String, String, Integer, Long, Long, LocalDateTime, LocalDateTime, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>redis_datasource.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>redis_datasource.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>redis_datasource.tenant_id</code>. 租户ID
     */
    public void setTenantId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>redis_datasource.tenant_id</code>. 租户ID
     */
    public String getTenantId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>redis_datasource.datasource_id</code>.
     */
    public void setDatasourceId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>redis_datasource.datasource_id</code>.
     */
    public String getDatasourceId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>redis_datasource.space_code</code>.
     */
    public void setSpaceCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>redis_datasource.space_code</code>.
     */
    public String getSpaceCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>redis_datasource.host</code>. 主机
     */
    public void setHost(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>redis_datasource.host</code>. 主机
     */
    public String getHost() {
        return (String) get(4);
    }

    /**
     * Setter for <code>redis_datasource.port</code>. 端口
     */
    public void setPort(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>redis_datasource.port</code>. 端口
     */
    public Integer getPort() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>redis_datasource.db</code>. 默认数据库
     */
    public void setDb(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>redis_datasource.db</code>. 默认数据库
     */
    public Integer getDb() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>redis_datasource.user</code>. 用户名
     */
    public void setUser(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>redis_datasource.user</code>. 用户名
     */
    public String getUser() {
        return (String) get(7);
    }

    /**
     * Setter for <code>redis_datasource.password</code>. 密码
     */
    public void setPassword(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>redis_datasource.password</code>. 密码
     */
    public String getPassword() {
        return (String) get(8);
    }

    /**
     * Setter for <code>redis_datasource.status</code>. 数据源状态
-1: 无笑
0: 生效
     */
    public void setStatus(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>redis_datasource.status</code>. 数据源状态
-1: 无笑
0: 生效
     */
    public Integer getStatus() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>redis_datasource.cuid</code>.
     */
    public void setCuid(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>redis_datasource.cuid</code>.
     */
    public Long getCuid() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>redis_datasource.muid</code>.
     */
    public void setMuid(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>redis_datasource.muid</code>.
     */
    public Long getMuid() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>redis_datasource.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>redis_datasource.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>redis_datasource.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>redis_datasource.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>redis_datasource.cu_name</code>.
     */
    public void setCuName(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>redis_datasource.cu_name</code>.
     */
    public String getCuName() {
        return (String) get(14);
    }

    /**
     * Setter for <code>redis_datasource.mu_name</code>.
     */
    public void setMuName(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>redis_datasource.mu_name</code>.
     */
    public String getMuName() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<Long, String, String, String, String, Integer, Integer, String, String, Integer, Long, Long, LocalDateTime, LocalDateTime, String, String> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<Long, String, String, String, String, Integer, Integer, String, String, Integer, Long, Long, LocalDateTime, LocalDateTime, String, String> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return RedisDatasource.REDIS_DATASOURCE.ID;
    }

    @Override
    public Field<String> field2() {
        return RedisDatasource.REDIS_DATASOURCE.TENANT_ID;
    }

    @Override
    public Field<String> field3() {
        return RedisDatasource.REDIS_DATASOURCE.DATASOURCE_ID;
    }

    @Override
    public Field<String> field4() {
        return RedisDatasource.REDIS_DATASOURCE.SPACE_CODE;
    }

    @Override
    public Field<String> field5() {
        return RedisDatasource.REDIS_DATASOURCE.HOST;
    }

    @Override
    public Field<Integer> field6() {
        return RedisDatasource.REDIS_DATASOURCE.PORT;
    }

    @Override
    public Field<Integer> field7() {
        return RedisDatasource.REDIS_DATASOURCE.DB;
    }

    @Override
    public Field<String> field8() {
        return RedisDatasource.REDIS_DATASOURCE.USER;
    }

    @Override
    public Field<String> field9() {
        return RedisDatasource.REDIS_DATASOURCE.PASSWORD;
    }

    @Override
    public Field<Integer> field10() {
        return RedisDatasource.REDIS_DATASOURCE.STATUS;
    }

    @Override
    public Field<Long> field11() {
        return RedisDatasource.REDIS_DATASOURCE.CUID;
    }

    @Override
    public Field<Long> field12() {
        return RedisDatasource.REDIS_DATASOURCE.MUID;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return RedisDatasource.REDIS_DATASOURCE.CTIME;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return RedisDatasource.REDIS_DATASOURCE.MTIME;
    }

    @Override
    public Field<String> field15() {
        return RedisDatasource.REDIS_DATASOURCE.CU_NAME;
    }

    @Override
    public Field<String> field16() {
        return RedisDatasource.REDIS_DATASOURCE.MU_NAME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTenantId();
    }

    @Override
    public String component3() {
        return getDatasourceId();
    }

    @Override
    public String component4() {
        return getSpaceCode();
    }

    @Override
    public String component5() {
        return getHost();
    }

    @Override
    public Integer component6() {
        return getPort();
    }

    @Override
    public Integer component7() {
        return getDb();
    }

    @Override
    public String component8() {
        return getUser();
    }

    @Override
    public String component9() {
        return getPassword();
    }

    @Override
    public Integer component10() {
        return getStatus();
    }

    @Override
    public Long component11() {
        return getCuid();
    }

    @Override
    public Long component12() {
        return getMuid();
    }

    @Override
    public LocalDateTime component13() {
        return getCtime();
    }

    @Override
    public LocalDateTime component14() {
        return getMtime();
    }

    @Override
    public String component15() {
        return getCuName();
    }

    @Override
    public String component16() {
        return getMuName();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTenantId();
    }

    @Override
    public String value3() {
        return getDatasourceId();
    }

    @Override
    public String value4() {
        return getSpaceCode();
    }

    @Override
    public String value5() {
        return getHost();
    }

    @Override
    public Integer value6() {
        return getPort();
    }

    @Override
    public Integer value7() {
        return getDb();
    }

    @Override
    public String value8() {
        return getUser();
    }

    @Override
    public String value9() {
        return getPassword();
    }

    @Override
    public Integer value10() {
        return getStatus();
    }

    @Override
    public Long value11() {
        return getCuid();
    }

    @Override
    public Long value12() {
        return getMuid();
    }

    @Override
    public LocalDateTime value13() {
        return getCtime();
    }

    @Override
    public LocalDateTime value14() {
        return getMtime();
    }

    @Override
    public String value15() {
        return getCuName();
    }

    @Override
    public String value16() {
        return getMuName();
    }

    @Override
    public RedisDatasourceRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public RedisDatasourceRecord value2(String value) {
        setTenantId(value);
        return this;
    }

    @Override
    public RedisDatasourceRecord value3(String value) {
        setDatasourceId(value);
        return this;
    }

    @Override
    public RedisDatasourceRecord value4(String value) {
        setSpaceCode(value);
        return this;
    }

    @Override
    public RedisDatasourceRecord value5(String value) {
        setHost(value);
        return this;
    }

    @Override
    public RedisDatasourceRecord value6(Integer value) {
        setPort(value);
        return this;
    }

    @Override
    public RedisDatasourceRecord value7(Integer value) {
        setDb(value);
        return this;
    }

    @Override
    public RedisDatasourceRecord value8(String value) {
        setUser(value);
        return this;
    }

    @Override
    public RedisDatasourceRecord value9(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public RedisDatasourceRecord value10(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public RedisDatasourceRecord value11(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public RedisDatasourceRecord value12(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public RedisDatasourceRecord value13(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public RedisDatasourceRecord value14(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public RedisDatasourceRecord value15(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public RedisDatasourceRecord value16(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public RedisDatasourceRecord values(Long value1, String value2, String value3, String value4, String value5, Integer value6, Integer value7, String value8, String value9, Integer value10, Long value11, Long value12, LocalDateTime value13, LocalDateTime value14, String value15, String value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RedisDatasourceRecord
     */
    public RedisDatasourceRecord() {
        super(RedisDatasource.REDIS_DATASOURCE);
    }

    /**
     * Create a detached, initialised RedisDatasourceRecord
     */
    public RedisDatasourceRecord(Long id, String tenantId, String datasourceId, String spaceCode, String host, Integer port, Integer db, String user, String password, Integer status, Long cuid, Long muid, LocalDateTime ctime, LocalDateTime mtime, String cuName, String muName) {
        super(RedisDatasource.REDIS_DATASOURCE);

        setId(id);
        setTenantId(tenantId);
        setDatasourceId(datasourceId);
        setSpaceCode(spaceCode);
        setHost(host);
        setPort(port);
        setDb(db);
        setUser(user);
        setPassword(password);
        setStatus(status);
        setCuid(cuid);
        setMuid(muid);
        setCtime(ctime);
        setMtime(mtime);
        setCuName(cuName);
        setMuName(muName);
    }
}
