/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.workflow.db.tables.records;


import com.ke.bella.workflow.db.repo.Operator;
import com.ke.bella.workflow.db.tables.WorkflowScheduling;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkflowSchedulingRecord extends UpdatableRecordImpl<WorkflowSchedulingRecord> implements Operator, Record14<Long, String, String, String, String, LocalDateTime, String, String, LocalDateTime, String, Long, LocalDateTime, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>workflow_scheduling.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>workflow_scheduling.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>workflow_scheduling.tenant_id</code>.
     */
    public void setTenantId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>workflow_scheduling.tenant_id</code>.
     */
    public String getTenantId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>workflow_scheduling.workflow_id</code>.
     */
    public void setWorkflowId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>workflow_scheduling.workflow_id</code>.
     */
    public String getWorkflowId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>workflow_scheduling.workflow_scheduling_id</code>.
     */
    public void setWorkflowSchedulingId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>workflow_scheduling.workflow_scheduling_id</code>.
     */
    public String getWorkflowSchedulingId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>workflow_scheduling.cron_expression</code>. cron表达式
     */
    public void setCronExpression(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>workflow_scheduling.cron_expression</code>. cron表达式
     */
    public String getCronExpression() {
        return (String) get(4);
    }

    /**
     * Setter for <code>workflow_scheduling.trigger_next_time</code>.
     */
    public void setTriggerNextTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>workflow_scheduling.trigger_next_time</code>.
     */
    public LocalDateTime getTriggerNextTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>workflow_scheduling.inputs</code>.
     */
    public void setInputs(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>workflow_scheduling.inputs</code>.
     */
    public String getInputs() {
        return (String) get(6);
    }

    /**
     * Setter for <code>workflow_scheduling.status</code>. 调度任务状态；
init:待执行
pending:已有线程在处理,等待提交workflow_run
running:workflow_run进行中
finished:已完成
error:出现异常
:canceled:取消
     */
    public void setStatus(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>workflow_scheduling.status</code>. 调度任务状态；
init:待执行
pending:已有线程在处理,等待提交workflow_run
running:workflow_run进行中
finished:已完成
error:出现异常
:canceled:取消
     */
    public String getStatus() {
        return (String) get(7);
    }

    /**
     * Setter for <code>workflow_scheduling.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>workflow_scheduling.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>workflow_scheduling.cu_name</code>.
     */
    public void setCuName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>workflow_scheduling.cu_name</code>.
     */
    public String getCuName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>workflow_scheduling.cuid</code>.
     */
    public void setCuid(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>workflow_scheduling.cuid</code>.
     */
    public Long getCuid() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>workflow_scheduling.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>workflow_scheduling.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>workflow_scheduling.mu_name</code>.
     */
    public void setMuName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>workflow_scheduling.mu_name</code>.
     */
    public String getMuName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>workflow_scheduling.muid</code>.
     */
    public void setMuid(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>workflow_scheduling.muid</code>.
     */
    public Long getMuid() {
        return (Long) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, String, String, String, String, LocalDateTime, String, String, LocalDateTime, String, Long, LocalDateTime, String, Long> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Long, String, String, String, String, LocalDateTime, String, String, LocalDateTime, String, Long, LocalDateTime, String, Long> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return WorkflowScheduling.WORKFLOW_SCHEDULING.ID;
    }

    @Override
    public Field<String> field2() {
        return WorkflowScheduling.WORKFLOW_SCHEDULING.TENANT_ID;
    }

    @Override
    public Field<String> field3() {
        return WorkflowScheduling.WORKFLOW_SCHEDULING.WORKFLOW_ID;
    }

    @Override
    public Field<String> field4() {
        return WorkflowScheduling.WORKFLOW_SCHEDULING.WORKFLOW_SCHEDULING_ID;
    }

    @Override
    public Field<String> field5() {
        return WorkflowScheduling.WORKFLOW_SCHEDULING.CRON_EXPRESSION;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return WorkflowScheduling.WORKFLOW_SCHEDULING.TRIGGER_NEXT_TIME;
    }

    @Override
    public Field<String> field7() {
        return WorkflowScheduling.WORKFLOW_SCHEDULING.INPUTS;
    }

    @Override
    public Field<String> field8() {
        return WorkflowScheduling.WORKFLOW_SCHEDULING.STATUS;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return WorkflowScheduling.WORKFLOW_SCHEDULING.CTIME;
    }

    @Override
    public Field<String> field10() {
        return WorkflowScheduling.WORKFLOW_SCHEDULING.CU_NAME;
    }

    @Override
    public Field<Long> field11() {
        return WorkflowScheduling.WORKFLOW_SCHEDULING.CUID;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return WorkflowScheduling.WORKFLOW_SCHEDULING.MTIME;
    }

    @Override
    public Field<String> field13() {
        return WorkflowScheduling.WORKFLOW_SCHEDULING.MU_NAME;
    }

    @Override
    public Field<Long> field14() {
        return WorkflowScheduling.WORKFLOW_SCHEDULING.MUID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTenantId();
    }

    @Override
    public String component3() {
        return getWorkflowId();
    }

    @Override
    public String component4() {
        return getWorkflowSchedulingId();
    }

    @Override
    public String component5() {
        return getCronExpression();
    }

    @Override
    public LocalDateTime component6() {
        return getTriggerNextTime();
    }

    @Override
    public String component7() {
        return getInputs();
    }

    @Override
    public String component8() {
        return getStatus();
    }

    @Override
    public LocalDateTime component9() {
        return getCtime();
    }

    @Override
    public String component10() {
        return getCuName();
    }

    @Override
    public Long component11() {
        return getCuid();
    }

    @Override
    public LocalDateTime component12() {
        return getMtime();
    }

    @Override
    public String component13() {
        return getMuName();
    }

    @Override
    public Long component14() {
        return getMuid();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTenantId();
    }

    @Override
    public String value3() {
        return getWorkflowId();
    }

    @Override
    public String value4() {
        return getWorkflowSchedulingId();
    }

    @Override
    public String value5() {
        return getCronExpression();
    }

    @Override
    public LocalDateTime value6() {
        return getTriggerNextTime();
    }

    @Override
    public String value7() {
        return getInputs();
    }

    @Override
    public String value8() {
        return getStatus();
    }

    @Override
    public LocalDateTime value9() {
        return getCtime();
    }

    @Override
    public String value10() {
        return getCuName();
    }

    @Override
    public Long value11() {
        return getCuid();
    }

    @Override
    public LocalDateTime value12() {
        return getMtime();
    }

    @Override
    public String value13() {
        return getMuName();
    }

    @Override
    public Long value14() {
        return getMuid();
    }

    @Override
    public WorkflowSchedulingRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public WorkflowSchedulingRecord value2(String value) {
        setTenantId(value);
        return this;
    }

    @Override
    public WorkflowSchedulingRecord value3(String value) {
        setWorkflowId(value);
        return this;
    }

    @Override
    public WorkflowSchedulingRecord value4(String value) {
        setWorkflowSchedulingId(value);
        return this;
    }

    @Override
    public WorkflowSchedulingRecord value5(String value) {
        setCronExpression(value);
        return this;
    }

    @Override
    public WorkflowSchedulingRecord value6(LocalDateTime value) {
        setTriggerNextTime(value);
        return this;
    }

    @Override
    public WorkflowSchedulingRecord value7(String value) {
        setInputs(value);
        return this;
    }

    @Override
    public WorkflowSchedulingRecord value8(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public WorkflowSchedulingRecord value9(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public WorkflowSchedulingRecord value10(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public WorkflowSchedulingRecord value11(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public WorkflowSchedulingRecord value12(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public WorkflowSchedulingRecord value13(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public WorkflowSchedulingRecord value14(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public WorkflowSchedulingRecord values(Long value1, String value2, String value3, String value4, String value5, LocalDateTime value6, String value7, String value8, LocalDateTime value9, String value10, Long value11, LocalDateTime value12, String value13, Long value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkflowSchedulingRecord
     */
    public WorkflowSchedulingRecord() {
        super(WorkflowScheduling.WORKFLOW_SCHEDULING);
    }

    /**
     * Create a detached, initialised WorkflowSchedulingRecord
     */
    public WorkflowSchedulingRecord(Long id, String tenantId, String workflowId, String workflowSchedulingId, String cronExpression, LocalDateTime triggerNextTime, String inputs, String status, LocalDateTime ctime, String cuName, Long cuid, LocalDateTime mtime, String muName, Long muid) {
        super(WorkflowScheduling.WORKFLOW_SCHEDULING);

        setId(id);
        setTenantId(tenantId);
        setWorkflowId(workflowId);
        setWorkflowSchedulingId(workflowSchedulingId);
        setCronExpression(cronExpression);
        setTriggerNextTime(triggerNextTime);
        setInputs(inputs);
        setStatus(status);
        setCtime(ctime);
        setCuName(cuName);
        setCuid(cuid);
        setMtime(mtime);
        setMuName(muName);
        setMuid(muid);
    }
}
