/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.workflow.db.tables.records;


import com.ke.bella.workflow.db.repo.Operator;
import com.ke.bella.workflow.db.tables.WorkflowTemplate;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkflowTemplateRecord extends UpdatableRecordImpl<WorkflowTemplateRecord> implements Operator, Record18<Long, String, String, String, String, Long, String, String, String, String, Integer, Long, Long, String, LocalDateTime, Long, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>workflow_template.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>workflow_template.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>workflow_template.tenant_id</code>. 租户id
     */
    public void setTenantId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>workflow_template.tenant_id</code>. 租户id
     */
    public String getTenantId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>workflow_template.space_code</code>.
     */
    public void setSpaceCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>workflow_template.space_code</code>.
     */
    public String getSpaceCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>workflow_template.template_id</code>.
     */
    public void setTemplateId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>workflow_template.template_id</code>.
     */
    public String getTemplateId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>workflow_template.workflow_id</code>.
     */
    public void setWorkflowId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>workflow_template.workflow_id</code>.
     */
    public String getWorkflowId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>workflow_template.version</code>.
     */
    public void setVersion(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>workflow_template.version</code>.
     */
    public Long getVersion() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>workflow_template.title</code>.
     */
    public void setTitle(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>workflow_template.title</code>.
     */
    public String getTitle() {
        return (String) get(6);
    }

    /**
     * Setter for <code>workflow_template.mode</code>.
     */
    public void setMode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>workflow_template.mode</code>.
     */
    public String getMode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>workflow_template.desc</code>.
     */
    public void setDesc(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>workflow_template.desc</code>.
     */
    public String getDesc() {
        return (String) get(8);
    }

    /**
     * Setter for <code>workflow_template.tags</code>. 标签
     */
    public void setTags(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>workflow_template.tags</code>. 标签
     */
    public String getTags() {
        return (String) get(9);
    }

    /**
     * Setter for <code>workflow_template.status</code>.
     */
    public void setStatus(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>workflow_template.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>workflow_template.copies</code>. 复制次数
     */
    public void setCopies(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>workflow_template.copies</code>. 复制次数
     */
    public Long getCopies() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>workflow_template.cuid</code>.
     */
    public void setCuid(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>workflow_template.cuid</code>.
     */
    public Long getCuid() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>workflow_template.cu_name</code>.
     */
    public void setCuName(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>workflow_template.cu_name</code>.
     */
    public String getCuName() {
        return (String) get(13);
    }

    /**
     * Setter for <code>workflow_template.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>workflow_template.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>workflow_template.muid</code>.
     */
    public void setMuid(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>workflow_template.muid</code>.
     */
    public Long getMuid() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>workflow_template.mu_name</code>.
     */
    public void setMuName(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>workflow_template.mu_name</code>.
     */
    public String getMuName() {
        return (String) get(16);
    }

    /**
     * Setter for <code>workflow_template.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(17, value);
    }

    /**
     * Getter for <code>workflow_template.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row18<Long, String, String, String, String, Long, String, String, String, String, Integer, Long, Long, String, LocalDateTime, Long, String, LocalDateTime> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    @Override
    public Row18<Long, String, String, String, String, Long, String, String, String, String, Integer, Long, Long, String, LocalDateTime, Long, String, LocalDateTime> valuesRow() {
        return (Row18) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return WorkflowTemplate.WORKFLOW_TEMPLATE.ID;
    }

    @Override
    public Field<String> field2() {
        return WorkflowTemplate.WORKFLOW_TEMPLATE.TENANT_ID;
    }

    @Override
    public Field<String> field3() {
        return WorkflowTemplate.WORKFLOW_TEMPLATE.SPACE_CODE;
    }

    @Override
    public Field<String> field4() {
        return WorkflowTemplate.WORKFLOW_TEMPLATE.TEMPLATE_ID;
    }

    @Override
    public Field<String> field5() {
        return WorkflowTemplate.WORKFLOW_TEMPLATE.WORKFLOW_ID;
    }

    @Override
    public Field<Long> field6() {
        return WorkflowTemplate.WORKFLOW_TEMPLATE.VERSION;
    }

    @Override
    public Field<String> field7() {
        return WorkflowTemplate.WORKFLOW_TEMPLATE.TITLE;
    }

    @Override
    public Field<String> field8() {
        return WorkflowTemplate.WORKFLOW_TEMPLATE.MODE;
    }

    @Override
    public Field<String> field9() {
        return WorkflowTemplate.WORKFLOW_TEMPLATE.DESC;
    }

    @Override
    public Field<String> field10() {
        return WorkflowTemplate.WORKFLOW_TEMPLATE.TAGS;
    }

    @Override
    public Field<Integer> field11() {
        return WorkflowTemplate.WORKFLOW_TEMPLATE.STATUS;
    }

    @Override
    public Field<Long> field12() {
        return WorkflowTemplate.WORKFLOW_TEMPLATE.COPIES;
    }

    @Override
    public Field<Long> field13() {
        return WorkflowTemplate.WORKFLOW_TEMPLATE.CUID;
    }

    @Override
    public Field<String> field14() {
        return WorkflowTemplate.WORKFLOW_TEMPLATE.CU_NAME;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return WorkflowTemplate.WORKFLOW_TEMPLATE.CTIME;
    }

    @Override
    public Field<Long> field16() {
        return WorkflowTemplate.WORKFLOW_TEMPLATE.MUID;
    }

    @Override
    public Field<String> field17() {
        return WorkflowTemplate.WORKFLOW_TEMPLATE.MU_NAME;
    }

    @Override
    public Field<LocalDateTime> field18() {
        return WorkflowTemplate.WORKFLOW_TEMPLATE.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTenantId();
    }

    @Override
    public String component3() {
        return getSpaceCode();
    }

    @Override
    public String component4() {
        return getTemplateId();
    }

    @Override
    public String component5() {
        return getWorkflowId();
    }

    @Override
    public Long component6() {
        return getVersion();
    }

    @Override
    public String component7() {
        return getTitle();
    }

    @Override
    public String component8() {
        return getMode();
    }

    @Override
    public String component9() {
        return getDesc();
    }

    @Override
    public String component10() {
        return getTags();
    }

    @Override
    public Integer component11() {
        return getStatus();
    }

    @Override
    public Long component12() {
        return getCopies();
    }

    @Override
    public Long component13() {
        return getCuid();
    }

    @Override
    public String component14() {
        return getCuName();
    }

    @Override
    public LocalDateTime component15() {
        return getCtime();
    }

    @Override
    public Long component16() {
        return getMuid();
    }

    @Override
    public String component17() {
        return getMuName();
    }

    @Override
    public LocalDateTime component18() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTenantId();
    }

    @Override
    public String value3() {
        return getSpaceCode();
    }

    @Override
    public String value4() {
        return getTemplateId();
    }

    @Override
    public String value5() {
        return getWorkflowId();
    }

    @Override
    public Long value6() {
        return getVersion();
    }

    @Override
    public String value7() {
        return getTitle();
    }

    @Override
    public String value8() {
        return getMode();
    }

    @Override
    public String value9() {
        return getDesc();
    }

    @Override
    public String value10() {
        return getTags();
    }

    @Override
    public Integer value11() {
        return getStatus();
    }

    @Override
    public Long value12() {
        return getCopies();
    }

    @Override
    public Long value13() {
        return getCuid();
    }

    @Override
    public String value14() {
        return getCuName();
    }

    @Override
    public LocalDateTime value15() {
        return getCtime();
    }

    @Override
    public Long value16() {
        return getMuid();
    }

    @Override
    public String value17() {
        return getMuName();
    }

    @Override
    public LocalDateTime value18() {
        return getMtime();
    }

    @Override
    public WorkflowTemplateRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public WorkflowTemplateRecord value2(String value) {
        setTenantId(value);
        return this;
    }

    @Override
    public WorkflowTemplateRecord value3(String value) {
        setSpaceCode(value);
        return this;
    }

    @Override
    public WorkflowTemplateRecord value4(String value) {
        setTemplateId(value);
        return this;
    }

    @Override
    public WorkflowTemplateRecord value5(String value) {
        setWorkflowId(value);
        return this;
    }

    @Override
    public WorkflowTemplateRecord value6(Long value) {
        setVersion(value);
        return this;
    }

    @Override
    public WorkflowTemplateRecord value7(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public WorkflowTemplateRecord value8(String value) {
        setMode(value);
        return this;
    }

    @Override
    public WorkflowTemplateRecord value9(String value) {
        setDesc(value);
        return this;
    }

    @Override
    public WorkflowTemplateRecord value10(String value) {
        setTags(value);
        return this;
    }

    @Override
    public WorkflowTemplateRecord value11(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public WorkflowTemplateRecord value12(Long value) {
        setCopies(value);
        return this;
    }

    @Override
    public WorkflowTemplateRecord value13(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public WorkflowTemplateRecord value14(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public WorkflowTemplateRecord value15(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public WorkflowTemplateRecord value16(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public WorkflowTemplateRecord value17(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public WorkflowTemplateRecord value18(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public WorkflowTemplateRecord values(Long value1, String value2, String value3, String value4, String value5, Long value6, String value7, String value8, String value9, String value10, Integer value11, Long value12, Long value13, String value14, LocalDateTime value15, Long value16, String value17, LocalDateTime value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkflowTemplateRecord
     */
    public WorkflowTemplateRecord() {
        super(WorkflowTemplate.WORKFLOW_TEMPLATE);
    }

    /**
     * Create a detached, initialised WorkflowTemplateRecord
     */
    public WorkflowTemplateRecord(Long id, String tenantId, String spaceCode, String templateId, String workflowId, Long version, String title, String mode, String desc, String tags, Integer status, Long copies, Long cuid, String cuName, LocalDateTime ctime, Long muid, String muName, LocalDateTime mtime) {
        super(WorkflowTemplate.WORKFLOW_TEMPLATE);

        setId(id);
        setTenantId(tenantId);
        setSpaceCode(spaceCode);
        setTemplateId(templateId);
        setWorkflowId(workflowId);
        setVersion(version);
        setTitle(title);
        setMode(mode);
        setDesc(desc);
        setTags(tags);
        setStatus(status);
        setCopies(copies);
        setCuid(cuid);
        setCuName(cuName);
        setCtime(ctime);
        setMuid(muid);
        setMuName(muName);
        setMtime(mtime);
    }
}
