/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.workflow.db.tables.records;


import com.ke.bella.workflow.db.repo.Operator;
import com.ke.bella.workflow.db.tables.WorkflowAsApi;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkflowAsApiRecord extends UpdatableRecordImpl<WorkflowAsApiRecord> implements Operator, Record17<Long, String, String, String, String, String, String, String, String, Long, Integer, Long, String, LocalDateTime, Long, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>workflow_as_api.id</code>. workflow配置自增主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>workflow_as_api.id</code>. workflow配置自增主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>workflow_as_api.host</code>. 绑定的域名
     */
    public void setHost(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>workflow_as_api.host</code>. 绑定的域名
     */
    public String getHost() {
        return (String) get(1);
    }

    /**
     * Setter for <code>workflow_as_api.path</code>. 绑定的api路径
     */
    public void setPath(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>workflow_as_api.path</code>. 绑定的api路径
     */
    public String getPath() {
        return (String) get(2);
    }

    /**
     * Setter for <code>workflow_as_api.hash</code>. host+path的hash
     */
    public void setHash(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>workflow_as_api.hash</code>. host+path的hash
     */
    public String getHash() {
        return (String) get(3);
    }

    /**
     * Setter for <code>workflow_as_api.operation_id</code>. 生成openapi schema的时候使用的operationId
     */
    public void setOperationId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>workflow_as_api.operation_id</code>. 生成openapi schema的时候使用的operationId
     */
    public String getOperationId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>workflow_as_api.tenant_id</code>. 租户id
     */
    public void setTenantId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>workflow_as_api.tenant_id</code>. 租户id
     */
    public String getTenantId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>workflow_as_api.workflow_id</code>. 工作流id
     */
    public void setWorkflowId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>workflow_as_api.workflow_id</code>. 工作流id
     */
    public String getWorkflowId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>workflow_as_api.summary</code>.
     */
    public void setSummary(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>workflow_as_api.summary</code>.
     */
    public String getSummary() {
        return (String) get(7);
    }

    /**
     * Setter for <code>workflow_as_api.desc</code>.
     */
    public void setDesc(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>workflow_as_api.desc</code>.
     */
    public String getDesc() {
        return (String) get(8);
    }

    /**
     * Setter for <code>workflow_as_api.version</code>. 工作流版本，0: draft, &gt;0 正式版时间戳
     */
    public void setVersion(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>workflow_as_api.version</code>. 工作流版本，0: draft, &gt;0 正式版时间戳
     */
    public Long getVersion() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>workflow_as_api.status</code>.
     */
    public void setStatus(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>workflow_as_api.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>workflow_as_api.cuid</code>.
     */
    public void setCuid(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>workflow_as_api.cuid</code>.
     */
    public Long getCuid() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>workflow_as_api.cu_name</code>.
     */
    public void setCuName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>workflow_as_api.cu_name</code>.
     */
    public String getCuName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>workflow_as_api.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>workflow_as_api.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>workflow_as_api.muid</code>.
     */
    public void setMuid(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>workflow_as_api.muid</code>.
     */
    public Long getMuid() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>workflow_as_api.mu_name</code>.
     */
    public void setMuName(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>workflow_as_api.mu_name</code>.
     */
    public String getMuName() {
        return (String) get(15);
    }

    /**
     * Setter for <code>workflow_as_api.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>workflow_as_api.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row17<Long, String, String, String, String, String, String, String, String, Long, Integer, Long, String, LocalDateTime, Long, String, LocalDateTime> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    @Override
    public Row17<Long, String, String, String, String, String, String, String, String, Long, Integer, Long, String, LocalDateTime, Long, String, LocalDateTime> valuesRow() {
        return (Row17) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return WorkflowAsApi.WORKFLOW_AS_API.ID;
    }

    @Override
    public Field<String> field2() {
        return WorkflowAsApi.WORKFLOW_AS_API.HOST;
    }

    @Override
    public Field<String> field3() {
        return WorkflowAsApi.WORKFLOW_AS_API.PATH;
    }

    @Override
    public Field<String> field4() {
        return WorkflowAsApi.WORKFLOW_AS_API.HASH;
    }

    @Override
    public Field<String> field5() {
        return WorkflowAsApi.WORKFLOW_AS_API.OPERATION_ID;
    }

    @Override
    public Field<String> field6() {
        return WorkflowAsApi.WORKFLOW_AS_API.TENANT_ID;
    }

    @Override
    public Field<String> field7() {
        return WorkflowAsApi.WORKFLOW_AS_API.WORKFLOW_ID;
    }

    @Override
    public Field<String> field8() {
        return WorkflowAsApi.WORKFLOW_AS_API.SUMMARY;
    }

    @Override
    public Field<String> field9() {
        return WorkflowAsApi.WORKFLOW_AS_API.DESC;
    }

    @Override
    public Field<Long> field10() {
        return WorkflowAsApi.WORKFLOW_AS_API.VERSION;
    }

    @Override
    public Field<Integer> field11() {
        return WorkflowAsApi.WORKFLOW_AS_API.STATUS;
    }

    @Override
    public Field<Long> field12() {
        return WorkflowAsApi.WORKFLOW_AS_API.CUID;
    }

    @Override
    public Field<String> field13() {
        return WorkflowAsApi.WORKFLOW_AS_API.CU_NAME;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return WorkflowAsApi.WORKFLOW_AS_API.CTIME;
    }

    @Override
    public Field<Long> field15() {
        return WorkflowAsApi.WORKFLOW_AS_API.MUID;
    }

    @Override
    public Field<String> field16() {
        return WorkflowAsApi.WORKFLOW_AS_API.MU_NAME;
    }

    @Override
    public Field<LocalDateTime> field17() {
        return WorkflowAsApi.WORKFLOW_AS_API.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getHost();
    }

    @Override
    public String component3() {
        return getPath();
    }

    @Override
    public String component4() {
        return getHash();
    }

    @Override
    public String component5() {
        return getOperationId();
    }

    @Override
    public String component6() {
        return getTenantId();
    }

    @Override
    public String component7() {
        return getWorkflowId();
    }

    @Override
    public String component8() {
        return getSummary();
    }

    @Override
    public String component9() {
        return getDesc();
    }

    @Override
    public Long component10() {
        return getVersion();
    }

    @Override
    public Integer component11() {
        return getStatus();
    }

    @Override
    public Long component12() {
        return getCuid();
    }

    @Override
    public String component13() {
        return getCuName();
    }

    @Override
    public LocalDateTime component14() {
        return getCtime();
    }

    @Override
    public Long component15() {
        return getMuid();
    }

    @Override
    public String component16() {
        return getMuName();
    }

    @Override
    public LocalDateTime component17() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getHost();
    }

    @Override
    public String value3() {
        return getPath();
    }

    @Override
    public String value4() {
        return getHash();
    }

    @Override
    public String value5() {
        return getOperationId();
    }

    @Override
    public String value6() {
        return getTenantId();
    }

    @Override
    public String value7() {
        return getWorkflowId();
    }

    @Override
    public String value8() {
        return getSummary();
    }

    @Override
    public String value9() {
        return getDesc();
    }

    @Override
    public Long value10() {
        return getVersion();
    }

    @Override
    public Integer value11() {
        return getStatus();
    }

    @Override
    public Long value12() {
        return getCuid();
    }

    @Override
    public String value13() {
        return getCuName();
    }

    @Override
    public LocalDateTime value14() {
        return getCtime();
    }

    @Override
    public Long value15() {
        return getMuid();
    }

    @Override
    public String value16() {
        return getMuName();
    }

    @Override
    public LocalDateTime value17() {
        return getMtime();
    }

    @Override
    public WorkflowAsApiRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public WorkflowAsApiRecord value2(String value) {
        setHost(value);
        return this;
    }

    @Override
    public WorkflowAsApiRecord value3(String value) {
        setPath(value);
        return this;
    }

    @Override
    public WorkflowAsApiRecord value4(String value) {
        setHash(value);
        return this;
    }

    @Override
    public WorkflowAsApiRecord value5(String value) {
        setOperationId(value);
        return this;
    }

    @Override
    public WorkflowAsApiRecord value6(String value) {
        setTenantId(value);
        return this;
    }

    @Override
    public WorkflowAsApiRecord value7(String value) {
        setWorkflowId(value);
        return this;
    }

    @Override
    public WorkflowAsApiRecord value8(String value) {
        setSummary(value);
        return this;
    }

    @Override
    public WorkflowAsApiRecord value9(String value) {
        setDesc(value);
        return this;
    }

    @Override
    public WorkflowAsApiRecord value10(Long value) {
        setVersion(value);
        return this;
    }

    @Override
    public WorkflowAsApiRecord value11(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public WorkflowAsApiRecord value12(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public WorkflowAsApiRecord value13(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public WorkflowAsApiRecord value14(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public WorkflowAsApiRecord value15(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public WorkflowAsApiRecord value16(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public WorkflowAsApiRecord value17(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public WorkflowAsApiRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, Long value10, Integer value11, Long value12, String value13, LocalDateTime value14, Long value15, String value16, LocalDateTime value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkflowAsApiRecord
     */
    public WorkflowAsApiRecord() {
        super(WorkflowAsApi.WORKFLOW_AS_API);
    }

    /**
     * Create a detached, initialised WorkflowAsApiRecord
     */
    public WorkflowAsApiRecord(Long id, String host, String path, String hash, String operationId, String tenantId, String workflowId, String summary, String desc, Long version, Integer status, Long cuid, String cuName, LocalDateTime ctime, Long muid, String muName, LocalDateTime mtime) {
        super(WorkflowAsApi.WORKFLOW_AS_API);

        setId(id);
        setHost(host);
        setPath(path);
        setHash(hash);
        setOperationId(operationId);
        setTenantId(tenantId);
        setWorkflowId(workflowId);
        setSummary(summary);
        setDesc(desc);
        setVersion(version);
        setStatus(status);
        setCuid(cuid);
        setCuName(cuName);
        setCtime(ctime);
        setMuid(muid);
        setMuName(muName);
        setMtime(mtime);
    }
}
