/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.workflow.db.tables.pojos;


import com.ke.bella.workflow.db.repo.Operator;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RedisDatasourceDB implements Operator, Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        tenantId;
    private String        datasourceId;
    private String        spaceCode;
    private String        host;
    private Integer       port;
    private Integer       db;
    private String        user;
    private String        password;
    private Integer       status;
    private Long          cuid;
    private Long          muid;
    private LocalDateTime ctime;
    private LocalDateTime mtime;
    private String        cuName;
    private String        muName;

    public RedisDatasourceDB() {}

    public RedisDatasourceDB(RedisDatasourceDB value) {
        this.id = value.id;
        this.tenantId = value.tenantId;
        this.datasourceId = value.datasourceId;
        this.spaceCode = value.spaceCode;
        this.host = value.host;
        this.port = value.port;
        this.db = value.db;
        this.user = value.user;
        this.password = value.password;
        this.status = value.status;
        this.cuid = value.cuid;
        this.muid = value.muid;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
        this.cuName = value.cuName;
        this.muName = value.muName;
    }

    public RedisDatasourceDB(
        Long          id,
        String        tenantId,
        String        datasourceId,
        String        spaceCode,
        String        host,
        Integer       port,
        Integer       db,
        String        user,
        String        password,
        Integer       status,
        Long          cuid,
        Long          muid,
        LocalDateTime ctime,
        LocalDateTime mtime,
        String        cuName,
        String        muName
    ) {
        this.id = id;
        this.tenantId = tenantId;
        this.datasourceId = datasourceId;
        this.spaceCode = spaceCode;
        this.host = host;
        this.port = port;
        this.db = db;
        this.user = user;
        this.password = password;
        this.status = status;
        this.cuid = cuid;
        this.muid = muid;
        this.ctime = ctime;
        this.mtime = mtime;
        this.cuName = cuName;
        this.muName = muName;
    }

    /**
     * Getter for <code>redis_datasource.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>redis_datasource.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>redis_datasource.tenant_id</code>. 租户ID
     */
    public String getTenantId() {
        return this.tenantId;
    }

    /**
     * Setter for <code>redis_datasource.tenant_id</code>. 租户ID
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * Getter for <code>redis_datasource.datasource_id</code>.
     */
    public String getDatasourceId() {
        return this.datasourceId;
    }

    /**
     * Setter for <code>redis_datasource.datasource_id</code>.
     */
    public void setDatasourceId(String datasourceId) {
        this.datasourceId = datasourceId;
    }

    /**
     * Getter for <code>redis_datasource.space_code</code>.
     */
    public String getSpaceCode() {
        return this.spaceCode;
    }

    /**
     * Setter for <code>redis_datasource.space_code</code>.
     */
    public void setSpaceCode(String spaceCode) {
        this.spaceCode = spaceCode;
    }

    /**
     * Getter for <code>redis_datasource.host</code>. 主机
     */
    public String getHost() {
        return this.host;
    }

    /**
     * Setter for <code>redis_datasource.host</code>. 主机
     */
    public void setHost(String host) {
        this.host = host;
    }

    /**
     * Getter for <code>redis_datasource.port</code>. 端口
     */
    public Integer getPort() {
        return this.port;
    }

    /**
     * Setter for <code>redis_datasource.port</code>. 端口
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * Getter for <code>redis_datasource.db</code>. 默认数据库
     */
    public Integer getDb() {
        return this.db;
    }

    /**
     * Setter for <code>redis_datasource.db</code>. 默认数据库
     */
    public void setDb(Integer db) {
        this.db = db;
    }

    /**
     * Getter for <code>redis_datasource.user</code>. 用户名
     */
    public String getUser() {
        return this.user;
    }

    /**
     * Setter for <code>redis_datasource.user</code>. 用户名
     */
    public void setUser(String user) {
        this.user = user;
    }

    /**
     * Getter for <code>redis_datasource.password</code>. 密码
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>redis_datasource.password</code>. 密码
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Getter for <code>redis_datasource.status</code>. 数据源状态
-1: 无笑
0: 生效
     */
    public Integer getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>redis_datasource.status</code>. 数据源状态
-1: 无笑
0: 生效
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * Getter for <code>redis_datasource.cuid</code>.
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>redis_datasource.cuid</code>.
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>redis_datasource.muid</code>.
     */
    public Long getMuid() {
        return this.muid;
    }

    /**
     * Setter for <code>redis_datasource.muid</code>.
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    /**
     * Getter for <code>redis_datasource.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>redis_datasource.ctime</code>.
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>redis_datasource.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>redis_datasource.mtime</code>.
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    /**
     * Getter for <code>redis_datasource.cu_name</code>.
     */
    public String getCuName() {
        return this.cuName;
    }

    /**
     * Setter for <code>redis_datasource.cu_name</code>.
     */
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    /**
     * Getter for <code>redis_datasource.mu_name</code>.
     */
    public String getMuName() {
        return this.muName;
    }

    /**
     * Setter for <code>redis_datasource.mu_name</code>.
     */
    public void setMuName(String muName) {
        this.muName = muName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RedisDatasourceDB (");

        sb.append(id);
        sb.append(", ").append(tenantId);
        sb.append(", ").append(datasourceId);
        sb.append(", ").append(spaceCode);
        sb.append(", ").append(host);
        sb.append(", ").append(port);
        sb.append(", ").append(db);
        sb.append(", ").append(user);
        sb.append(", ").append(password);
        sb.append(", ").append(status);
        sb.append(", ").append(cuid);
        sb.append(", ").append(muid);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);
        sb.append(", ").append(cuName);
        sb.append(", ").append(muName);

        sb.append(")");
        return sb.toString();
    }
}
