/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.workflow.db.tables.pojos;


import com.ke.bella.workflow.db.repo.Operator;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkflowNodeRunTempDB implements Operator, Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        tenantId;
    private String        workflowId;
    private String        workflowRunId;
    private String        nodeRunId;
    private String        nodeId;
    private String        nodeType;
    private String        title;
    private String        inputs;
    private String        outputs;
    private String        error;
    private String        processData;
    private String        notifyData;
    private String        activedTargetHandles;
    private String        status;
    private Long          elapsedTime;
    private Long          cuid;
    private String        cuName;
    private LocalDateTime ctime;
    private Long          muid;
    private String        muName;
    private LocalDateTime mtime;

    public WorkflowNodeRunTempDB() {}

    public WorkflowNodeRunTempDB(WorkflowNodeRunTempDB value) {
        this.id = value.id;
        this.tenantId = value.tenantId;
        this.workflowId = value.workflowId;
        this.workflowRunId = value.workflowRunId;
        this.nodeRunId = value.nodeRunId;
        this.nodeId = value.nodeId;
        this.nodeType = value.nodeType;
        this.title = value.title;
        this.inputs = value.inputs;
        this.outputs = value.outputs;
        this.error = value.error;
        this.processData = value.processData;
        this.notifyData = value.notifyData;
        this.activedTargetHandles = value.activedTargetHandles;
        this.status = value.status;
        this.elapsedTime = value.elapsedTime;
        this.cuid = value.cuid;
        this.cuName = value.cuName;
        this.ctime = value.ctime;
        this.muid = value.muid;
        this.muName = value.muName;
        this.mtime = value.mtime;
    }

    public WorkflowNodeRunTempDB(
        Long          id,
        String        tenantId,
        String        workflowId,
        String        workflowRunId,
        String        nodeRunId,
        String        nodeId,
        String        nodeType,
        String        title,
        String        inputs,
        String        outputs,
        String        error,
        String        processData,
        String        notifyData,
        String        activedTargetHandles,
        String        status,
        Long          elapsedTime,
        Long          cuid,
        String        cuName,
        LocalDateTime ctime,
        Long          muid,
        String        muName,
        LocalDateTime mtime
    ) {
        this.id = id;
        this.tenantId = tenantId;
        this.workflowId = workflowId;
        this.workflowRunId = workflowRunId;
        this.nodeRunId = nodeRunId;
        this.nodeId = nodeId;
        this.nodeType = nodeType;
        this.title = title;
        this.inputs = inputs;
        this.outputs = outputs;
        this.error = error;
        this.processData = processData;
        this.notifyData = notifyData;
        this.activedTargetHandles = activedTargetHandles;
        this.status = status;
        this.elapsedTime = elapsedTime;
        this.cuid = cuid;
        this.cuName = cuName;
        this.ctime = ctime;
        this.muid = muid;
        this.muName = muName;
        this.mtime = mtime;
    }

    /**
     * Getter for <code>workflow_node_run_temp.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>workflow_node_run_temp.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>workflow_node_run_temp.tenant_id</code>.
     */
    public String getTenantId() {
        return this.tenantId;
    }

    /**
     * Setter for <code>workflow_node_run_temp.tenant_id</code>.
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * Getter for <code>workflow_node_run_temp.workflow_id</code>.
     */
    public String getWorkflowId() {
        return this.workflowId;
    }

    /**
     * Setter for <code>workflow_node_run_temp.workflow_id</code>.
     */
    public void setWorkflowId(String workflowId) {
        this.workflowId = workflowId;
    }

    /**
     * Getter for <code>workflow_node_run_temp.workflow_run_id</code>.
     */
    public String getWorkflowRunId() {
        return this.workflowRunId;
    }

    /**
     * Setter for <code>workflow_node_run_temp.workflow_run_id</code>.
     */
    public void setWorkflowRunId(String workflowRunId) {
        this.workflowRunId = workflowRunId;
    }

    /**
     * Getter for <code>workflow_node_run_temp.node_run_id</code>.
     */
    public String getNodeRunId() {
        return this.nodeRunId;
    }

    /**
     * Setter for <code>workflow_node_run_temp.node_run_id</code>.
     */
    public void setNodeRunId(String nodeRunId) {
        this.nodeRunId = nodeRunId;
    }

    /**
     * Getter for <code>workflow_node_run_temp.node_id</code>.
     */
    public String getNodeId() {
        return this.nodeId;
    }

    /**
     * Setter for <code>workflow_node_run_temp.node_id</code>.
     */
    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * Getter for <code>workflow_node_run_temp.node_type</code>.
     */
    public String getNodeType() {
        return this.nodeType;
    }

    /**
     * Setter for <code>workflow_node_run_temp.node_type</code>.
     */
    public void setNodeType(String nodeType) {
        this.nodeType = nodeType;
    }

    /**
     * Getter for <code>workflow_node_run_temp.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>workflow_node_run_temp.title</code>.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>workflow_node_run_temp.inputs</code>.
     */
    public String getInputs() {
        return this.inputs;
    }

    /**
     * Setter for <code>workflow_node_run_temp.inputs</code>.
     */
    public void setInputs(String inputs) {
        this.inputs = inputs;
    }

    /**
     * Getter for <code>workflow_node_run_temp.outputs</code>.
     */
    public String getOutputs() {
        return this.outputs;
    }

    /**
     * Setter for <code>workflow_node_run_temp.outputs</code>.
     */
    public void setOutputs(String outputs) {
        this.outputs = outputs;
    }

    /**
     * Getter for <code>workflow_node_run_temp.error</code>.
     */
    public String getError() {
        return this.error;
    }

    /**
     * Setter for <code>workflow_node_run_temp.error</code>.
     */
    public void setError(String error) {
        this.error = error;
    }

    /**
     * Getter for <code>workflow_node_run_temp.process_data</code>.
     */
    public String getProcessData() {
        return this.processData;
    }

    /**
     * Setter for <code>workflow_node_run_temp.process_data</code>.
     */
    public void setProcessData(String processData) {
        this.processData = processData;
    }

    /**
     * Getter for <code>workflow_node_run_temp.notify_data</code>.
     */
    public String getNotifyData() {
        return this.notifyData;
    }

    /**
     * Setter for <code>workflow_node_run_temp.notify_data</code>.
     */
    public void setNotifyData(String notifyData) {
        this.notifyData = notifyData;
    }

    /**
     * Getter for <code>workflow_node_run_temp.actived_target_handles</code>.
     */
    public String getActivedTargetHandles() {
        return this.activedTargetHandles;
    }

    /**
     * Setter for <code>workflow_node_run_temp.actived_target_handles</code>.
     */
    public void setActivedTargetHandles(String activedTargetHandles) {
        this.activedTargetHandles = activedTargetHandles;
    }

    /**
     * Getter for <code>workflow_node_run_temp.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>workflow_node_run_temp.status</code>.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>workflow_node_run_temp.elapsed_time</code>.
     */
    public Long getElapsedTime() {
        return this.elapsedTime;
    }

    /**
     * Setter for <code>workflow_node_run_temp.elapsed_time</code>.
     */
    public void setElapsedTime(Long elapsedTime) {
        this.elapsedTime = elapsedTime;
    }

    /**
     * Getter for <code>workflow_node_run_temp.cuid</code>.
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>workflow_node_run_temp.cuid</code>.
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>workflow_node_run_temp.cu_name</code>.
     */
    public String getCuName() {
        return this.cuName;
    }

    /**
     * Setter for <code>workflow_node_run_temp.cu_name</code>.
     */
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    /**
     * Getter for <code>workflow_node_run_temp.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>workflow_node_run_temp.ctime</code>.
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>workflow_node_run_temp.muid</code>.
     */
    public Long getMuid() {
        return this.muid;
    }

    /**
     * Setter for <code>workflow_node_run_temp.muid</code>.
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    /**
     * Getter for <code>workflow_node_run_temp.mu_name</code>.
     */
    public String getMuName() {
        return this.muName;
    }

    /**
     * Setter for <code>workflow_node_run_temp.mu_name</code>.
     */
    public void setMuName(String muName) {
        this.muName = muName;
    }

    /**
     * Getter for <code>workflow_node_run_temp.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>workflow_node_run_temp.mtime</code>.
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WorkflowNodeRunTempDB (");

        sb.append(id);
        sb.append(", ").append(tenantId);
        sb.append(", ").append(workflowId);
        sb.append(", ").append(workflowRunId);
        sb.append(", ").append(nodeRunId);
        sb.append(", ").append(nodeId);
        sb.append(", ").append(nodeType);
        sb.append(", ").append(title);
        sb.append(", ").append(inputs);
        sb.append(", ").append(outputs);
        sb.append(", ").append(error);
        sb.append(", ").append(processData);
        sb.append(", ").append(notifyData);
        sb.append(", ").append(activedTargetHandles);
        sb.append(", ").append(status);
        sb.append(", ").append(elapsedTime);
        sb.append(", ").append(cuid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(muid);
        sb.append(", ").append(muName);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
