/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.workflow.db.tables.pojos;


import com.ke.bella.workflow.db.repo.Operator;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkflowSchedulingDB implements Operator, Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        tenantId;
    private String        triggerId;
    private String        triggerType;
    private String        workflowId;
    private String        workflowSchedulingId;
    private String        cronExpression;
    private LocalDateTime triggerNextTime;
    private String        inputs;
    private String        status;
    private LocalDateTime ctime;
    private String        cuName;
    private Long          cuid;
    private LocalDateTime mtime;
    private String        muName;
    private Long          muid;

    public WorkflowSchedulingDB() {}

    public WorkflowSchedulingDB(WorkflowSchedulingDB value) {
        this.id = value.id;
        this.tenantId = value.tenantId;
        this.triggerId = value.triggerId;
        this.triggerType = value.triggerType;
        this.workflowId = value.workflowId;
        this.workflowSchedulingId = value.workflowSchedulingId;
        this.cronExpression = value.cronExpression;
        this.triggerNextTime = value.triggerNextTime;
        this.inputs = value.inputs;
        this.status = value.status;
        this.ctime = value.ctime;
        this.cuName = value.cuName;
        this.cuid = value.cuid;
        this.mtime = value.mtime;
        this.muName = value.muName;
        this.muid = value.muid;
    }

    public WorkflowSchedulingDB(
        Long          id,
        String        tenantId,
        String        triggerId,
        String        triggerType,
        String        workflowId,
        String        workflowSchedulingId,
        String        cronExpression,
        LocalDateTime triggerNextTime,
        String        inputs,
        String        status,
        LocalDateTime ctime,
        String        cuName,
        Long          cuid,
        LocalDateTime mtime,
        String        muName,
        Long          muid
    ) {
        this.id = id;
        this.tenantId = tenantId;
        this.triggerId = triggerId;
        this.triggerType = triggerType;
        this.workflowId = workflowId;
        this.workflowSchedulingId = workflowSchedulingId;
        this.cronExpression = cronExpression;
        this.triggerNextTime = triggerNextTime;
        this.inputs = inputs;
        this.status = status;
        this.ctime = ctime;
        this.cuName = cuName;
        this.cuid = cuid;
        this.mtime = mtime;
        this.muName = muName;
        this.muid = muid;
    }

    /**
     * Getter for <code>workflow_scheduling.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>workflow_scheduling.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>workflow_scheduling.tenant_id</code>.
     */
    public String getTenantId() {
        return this.tenantId;
    }

    /**
     * Setter for <code>workflow_scheduling.tenant_id</code>.
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * Getter for <code>workflow_scheduling.trigger_id</code>.
     */
    public String getTriggerId() {
        return this.triggerId;
    }

    /**
     * Setter for <code>workflow_scheduling.trigger_id</code>.
     */
    public void setTriggerId(String triggerId) {
        this.triggerId = triggerId;
    }

    /**
     * Getter for <code>workflow_scheduling.trigger_type</code>.
     */
    public String getTriggerType() {
        return this.triggerType;
    }

    /**
     * Setter for <code>workflow_scheduling.trigger_type</code>.
     */
    public void setTriggerType(String triggerType) {
        this.triggerType = triggerType;
    }

    /**
     * Getter for <code>workflow_scheduling.workflow_id</code>.
     */
    public String getWorkflowId() {
        return this.workflowId;
    }

    /**
     * Setter for <code>workflow_scheduling.workflow_id</code>.
     */
    public void setWorkflowId(String workflowId) {
        this.workflowId = workflowId;
    }

    /**
     * Getter for <code>workflow_scheduling.workflow_scheduling_id</code>.
     */
    public String getWorkflowSchedulingId() {
        return this.workflowSchedulingId;
    }

    /**
     * Setter for <code>workflow_scheduling.workflow_scheduling_id</code>.
     */
    public void setWorkflowSchedulingId(String workflowSchedulingId) {
        this.workflowSchedulingId = workflowSchedulingId;
    }

    /**
     * Getter for <code>workflow_scheduling.cron_expression</code>. cron表达式
     */
    public String getCronExpression() {
        return this.cronExpression;
    }

    /**
     * Setter for <code>workflow_scheduling.cron_expression</code>. cron表达式
     */
    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression;
    }

    /**
     * Getter for <code>workflow_scheduling.trigger_next_time</code>.
     */
    public LocalDateTime getTriggerNextTime() {
        return this.triggerNextTime;
    }

    /**
     * Setter for <code>workflow_scheduling.trigger_next_time</code>.
     */
    public void setTriggerNextTime(LocalDateTime triggerNextTime) {
        this.triggerNextTime = triggerNextTime;
    }

    /**
     * Getter for <code>workflow_scheduling.inputs</code>.
     */
    public String getInputs() {
        return this.inputs;
    }

    /**
     * Setter for <code>workflow_scheduling.inputs</code>.
     */
    public void setInputs(String inputs) {
        this.inputs = inputs;
    }

    /**
     * Getter for <code>workflow_scheduling.status</code>. 调度任务状态；
init:待执行
pending:已有线程在处理,等待提交workflow_run
running:workflow_run进行中
finished:已完成
error:出现异常
:canceled:取消
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>workflow_scheduling.status</code>. 调度任务状态；
init:待执行
pending:已有线程在处理,等待提交workflow_run
running:workflow_run进行中
finished:已完成
error:出现异常
:canceled:取消
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>workflow_scheduling.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>workflow_scheduling.ctime</code>.
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>workflow_scheduling.cu_name</code>.
     */
    public String getCuName() {
        return this.cuName;
    }

    /**
     * Setter for <code>workflow_scheduling.cu_name</code>.
     */
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    /**
     * Getter for <code>workflow_scheduling.cuid</code>.
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>workflow_scheduling.cuid</code>.
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>workflow_scheduling.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>workflow_scheduling.mtime</code>.
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    /**
     * Getter for <code>workflow_scheduling.mu_name</code>.
     */
    public String getMuName() {
        return this.muName;
    }

    /**
     * Setter for <code>workflow_scheduling.mu_name</code>.
     */
    public void setMuName(String muName) {
        this.muName = muName;
    }

    /**
     * Getter for <code>workflow_scheduling.muid</code>.
     */
    public Long getMuid() {
        return this.muid;
    }

    /**
     * Setter for <code>workflow_scheduling.muid</code>.
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WorkflowSchedulingDB (");

        sb.append(id);
        sb.append(", ").append(tenantId);
        sb.append(", ").append(triggerId);
        sb.append(", ").append(triggerType);
        sb.append(", ").append(workflowId);
        sb.append(", ").append(workflowSchedulingId);
        sb.append(", ").append(cronExpression);
        sb.append(", ").append(triggerNextTime);
        sb.append(", ").append(inputs);
        sb.append(", ").append(status);
        sb.append(", ").append(ctime);
        sb.append(", ").append(cuName);
        sb.append(", ").append(cuid);
        sb.append(", ").append(mtime);
        sb.append(", ").append(muName);
        sb.append(", ").append(muid);

        sb.append(")");
        return sb.toString();
    }
}
