/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.workflow.db.tables.pojos;


import com.ke.bella.workflow.db.repo.Operator;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkflowAsApiDB implements Operator, Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        host;
    private String        path;
    private String        hash;
    private String        operationId;
    private String        tenantId;
    private String        workflowId;
    private String        summary;
    private String        desc;
    private Long          version;
    private Integer       status;
    private Long          cuid;
    private String        cuName;
    private LocalDateTime ctime;
    private Long          muid;
    private String        muName;
    private LocalDateTime mtime;

    public WorkflowAsApiDB() {}

    public WorkflowAsApiDB(WorkflowAsApiDB value) {
        this.id = value.id;
        this.host = value.host;
        this.path = value.path;
        this.hash = value.hash;
        this.operationId = value.operationId;
        this.tenantId = value.tenantId;
        this.workflowId = value.workflowId;
        this.summary = value.summary;
        this.desc = value.desc;
        this.version = value.version;
        this.status = value.status;
        this.cuid = value.cuid;
        this.cuName = value.cuName;
        this.ctime = value.ctime;
        this.muid = value.muid;
        this.muName = value.muName;
        this.mtime = value.mtime;
    }

    public WorkflowAsApiDB(
        Long          id,
        String        host,
        String        path,
        String        hash,
        String        operationId,
        String        tenantId,
        String        workflowId,
        String        summary,
        String        desc,
        Long          version,
        Integer       status,
        Long          cuid,
        String        cuName,
        LocalDateTime ctime,
        Long          muid,
        String        muName,
        LocalDateTime mtime
    ) {
        this.id = id;
        this.host = host;
        this.path = path;
        this.hash = hash;
        this.operationId = operationId;
        this.tenantId = tenantId;
        this.workflowId = workflowId;
        this.summary = summary;
        this.desc = desc;
        this.version = version;
        this.status = status;
        this.cuid = cuid;
        this.cuName = cuName;
        this.ctime = ctime;
        this.muid = muid;
        this.muName = muName;
        this.mtime = mtime;
    }

    /**
     * Getter for <code>workflow_as_api.id</code>. workflow配置自增主键
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>workflow_as_api.id</code>. workflow配置自增主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>workflow_as_api.host</code>. 绑定的域名
     */
    public String getHost() {
        return this.host;
    }

    /**
     * Setter for <code>workflow_as_api.host</code>. 绑定的域名
     */
    public void setHost(String host) {
        this.host = host;
    }

    /**
     * Getter for <code>workflow_as_api.path</code>. 绑定的api路径
     */
    public String getPath() {
        return this.path;
    }

    /**
     * Setter for <code>workflow_as_api.path</code>. 绑定的api路径
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * Getter for <code>workflow_as_api.hash</code>. host+path的hash
     */
    public String getHash() {
        return this.hash;
    }

    /**
     * Setter for <code>workflow_as_api.hash</code>. host+path的hash
     */
    public void setHash(String hash) {
        this.hash = hash;
    }

    /**
     * Getter for <code>workflow_as_api.operation_id</code>. 生成openapi schema的时候使用的operationId
     */
    public String getOperationId() {
        return this.operationId;
    }

    /**
     * Setter for <code>workflow_as_api.operation_id</code>. 生成openapi schema的时候使用的operationId
     */
    public void setOperationId(String operationId) {
        this.operationId = operationId;
    }

    /**
     * Getter for <code>workflow_as_api.tenant_id</code>. 租户id
     */
    public String getTenantId() {
        return this.tenantId;
    }

    /**
     * Setter for <code>workflow_as_api.tenant_id</code>. 租户id
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * Getter for <code>workflow_as_api.workflow_id</code>. 工作流id
     */
    public String getWorkflowId() {
        return this.workflowId;
    }

    /**
     * Setter for <code>workflow_as_api.workflow_id</code>. 工作流id
     */
    public void setWorkflowId(String workflowId) {
        this.workflowId = workflowId;
    }

    /**
     * Getter for <code>workflow_as_api.summary</code>.
     */
    public String getSummary() {
        return this.summary;
    }

    /**
     * Setter for <code>workflow_as_api.summary</code>.
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * Getter for <code>workflow_as_api.desc</code>.
     */
    public String getDesc() {
        return this.desc;
    }

    /**
     * Setter for <code>workflow_as_api.desc</code>.
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * Getter for <code>workflow_as_api.version</code>. 工作流版本，0: draft, &gt;0 正式版时间戳
     */
    public Long getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>workflow_as_api.version</code>. 工作流版本，0: draft, &gt;0 正式版时间戳
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * Getter for <code>workflow_as_api.status</code>.
     */
    public Integer getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>workflow_as_api.status</code>.
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * Getter for <code>workflow_as_api.cuid</code>.
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>workflow_as_api.cuid</code>.
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>workflow_as_api.cu_name</code>.
     */
    public String getCuName() {
        return this.cuName;
    }

    /**
     * Setter for <code>workflow_as_api.cu_name</code>.
     */
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    /**
     * Getter for <code>workflow_as_api.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>workflow_as_api.ctime</code>.
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>workflow_as_api.muid</code>.
     */
    public Long getMuid() {
        return this.muid;
    }

    /**
     * Setter for <code>workflow_as_api.muid</code>.
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    /**
     * Getter for <code>workflow_as_api.mu_name</code>.
     */
    public String getMuName() {
        return this.muName;
    }

    /**
     * Setter for <code>workflow_as_api.mu_name</code>.
     */
    public void setMuName(String muName) {
        this.muName = muName;
    }

    /**
     * Getter for <code>workflow_as_api.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>workflow_as_api.mtime</code>.
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WorkflowAsApiDB (");

        sb.append(id);
        sb.append(", ").append(host);
        sb.append(", ").append(path);
        sb.append(", ").append(hash);
        sb.append(", ").append(operationId);
        sb.append(", ").append(tenantId);
        sb.append(", ").append(workflowId);
        sb.append(", ").append(summary);
        sb.append(", ").append(desc);
        sb.append(", ").append(version);
        sb.append(", ").append(status);
        sb.append(", ").append(cuid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(muid);
        sb.append(", ").append(muName);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
